# Çalışan el kitabı: giriş bölümleri (ürün, sözlük, kurallar, araçlar, akış)

PRODUCT = [
("Simple Trading Journal nedir?","Trader'ların (borsada ya da döviz piyasasında alım satım yapan insanların) işlemlerini otomatik kaydeden bir online defterdir. Trader bir işlem yapar; program işlemi kendisi deftere yazar. Sonra trader bu defterden 'neyi doğru, neyi yanlış yapıyorum?' sorusunun cevabını görür. Adres: simpletradejournal.io"),
("Biz ne satıyoruz?","Bir yazılım satıyoruz. Para kazandırmayı, hisse önermeyi, 'şunu al şunu sat' demeyi satmıyoruz. Bu çok önemli: biz bir araç şirketiyiz, yatırım danışmanı değiliz."),
("Müşteri kim?","Her gün işlem yapan bireysel trader'lar ve 'prop firma' (fon sağlayan firma) hesabıyla çalışanlar. Çoğu MetaTrader adlı programı kullanır. Bizim program MetaTrader'daki işlemleri otomatik çeker."),
("Planlar ve fiyat","İki plan var. ÜCRETSİZ plan (kart gerekmez): 1 journal; günde 2 işlem (fazlası silinmez, kilitli saklanır); MetaTrader otomatik kayıt ve dosya içe aktarma; tüm istatistikler, takvim ve disiplin analizi; seanslar, günün haberleri, prop değerlendirme. PRO plan: her gün sınırsız işlem ve journal, sesli not ve yapay zekâ analizi, işlem öncesi ve sonrası 3'er fotoğraf. Pro 3 gün kartsız denenebilir. ÖNEMLİ: Pro şu an satın alınamıyor (ödeme sistemi şirket kurulunca açılacak). Bu yüzden içeriklerde ve cevaplarda FİYAT YAZMA. Fiyat soran olursa: 'Ücretsiz plan var, Pro 3 gün kartsız denenebilir; ücretli plan fiyatı ödeme açılınca duyurulacak.'"),
("Neyi öne çıkarırız?","(1) MetaTrader'dan işlemler kendiliğinden gelir, elle yazılmaz. (2) 'Hata analizi': intikam işlemi, aşırı işlem gibi alışkanlıkları gösterir. (3) Prop firma kuralına ne kadar yaklaşıldığını gösterir. (4) 9 dilde. (5) Ücretsiz hesap makineleri. (6) Pro planda sesli not, yapay zekâ analizi ve işlem fotoğrafları."),
("İçerik ekibinin işi ne?","Trader'lara yardım eden içerikler üretmek: eğitici videolar, kartlar, yazılar, hesap makineleri. Böylece insanlar bizi tanır, güvenir ve siteyi dener. Satış yapmaya çalışmayız; yardım ederiz, merak eden siteye gelir."),
]

# (terim, basit anlatım, örnek)
GLOSSARY = [
("Trader","Alım satım yapan kişi.","Ahmet her gün dolar/euro alıp satıyor. Ahmet bir trader."),
("İşlem (trade)","Bir alım ve ona karşılık gelen satım.","Sabah 10:00'da euro aldı, öğlen 12:00'de sattı. Bu 1 işlem."),
("Journal (işlem günlüğü)","Yapılan işlemlerin yazıldığı defter. Okul defteri gibi düşün; ama her işlemi, neden yaptığını ve ne olduğunu yazarsın.","'Bugün 3 işlem yaptım, 2'si zararla bitti, çünkü acele ettim.'"),
("MetaTrader (MT4, MT5)","Trader'ların kullandığı en yaygın işlem programı. Bizim program bunun içindeki işlemleri otomatik alır.","Müşteri MT5'te işlem yapar, bizim deftere kendiliğinden düşer."),
("Prop firma","Trader'a para veren (fon sağlayan) şirket. Trader belli kurallara uyarsa o parayla işlem yapar; kuralı bozarsa hesabı kapanır.","FTMO, The5ers gibi firmalar."),
("Günlük kayıp limiti","Prop firmanın bir günde kaybedilmesine izin verdiği en büyük para.","Limit 500 dolar. Bugün 500 dolar kaybeden trader'ın hesabı kapanabilir."),
("Drawdown","Hesabın en yüksek noktasından ne kadar düştüğü.","Hesap 10.000 dolara çıkmış, sonra 9.000 dolara düşmüş. Drawdown 1.000 dolar."),
("Risk","Bir işlemde kaybetmeyi göze aldığın para.","Hesabın 10.000 dolar. 'Bir işlemde en fazla 100 dolar kaybederim' dersen risk %1."),
("Pozisyon büyüklüğü (lot)","Bir işleme ne kadar büyük girdiğin. Büyüklüğü doğru ayarlamak, riski kontrol etmenin yoludur.","Aynı fiyat hareketinde büyük pozisyon büyük kayıp, küçük pozisyon küçük kayıp demektir."),
("R-multiple (R değeri)","Bir işlemin kazancını ya da kaybını, o işlemde göze aldığın riske bölerek bulunan sayı. Farklı büyüklükteki işlemleri aynı ölçüyle kıyaslar.","100 dolar riske ettin, 200 dolar kazandın: +2R. 100 dolar kaybettin: -1R."),
("Beklenti","Ortalama olarak her işlemden ne kadar kazanıp kaybettiğin.","Pozitif beklenti: uzun vadede kazandıran yöntem. Negatif: kaybettiren yöntem."),
("Kâr faktörü","Toplam kazancın, toplam kayba oranı.","Toplam kazanç 3.000, toplam kayıp 2.000: kâr faktörü 1,5."),
("Win rate (kazanma oranı)","İşlemlerin yüzde kaçının kârla bittiği.","10 işlemin 4'ü kârlı: win rate %40."),
("İntikam işlemi (revenge trading)","Bir kayıptan sonra, kaybı hemen geri almak için mantıksız işlem açmak.","Sabah 100 dolar kaybetti, öfkeyle hemen yeni işlem açtı. Bu intikam işlemi."),
("Aşırı işlem (overtrading)","Gereğinden çok işlem açmak.","Planı günde 3 işlemken 15 işlem açmak."),
("Demo / örnek veri","Gerçek olmayan, deneme için kullanılan hesap ya da rakam. Bizim içeriklerde gerçek kullanıcının verisini ASLA kullanmayız; hep örnek veri.","'Örnek hesap, gerçek değildir' diye yazılır."),
("Reels / Shorts / TikTok","Dikey (telefonu dik tutarak izlenen), kısa videolar. Instagram'da adı Reels, YouTube'da Shorts, TikTok'ta TikTok.","Aynı 45 saniyelik video üçüne de yüklenir."),
("Story (hikâye)","24 saat sonra kaybolan kısa paylaşım (Instagram'da).","Sabah 'bugünün kuralı' kartı koymak."),
("Karusel","Kaydırmalı, birden çok görselden oluşan gönderi. Kartlara bakıp sağa kaydırırsın.","'Pozisyon büyüklüğü 5 adımda' diye 6 kartlık gönderi."),
("Thread","X'te (Twitter) art arda bağlı tweetler. Bir konuyu parça parça anlatır.","1/6, 2/6 ... diye giden tweet dizisi."),
("Thumbnail (kapak resmi)","YouTube videosunun liste üzerindeki küçük resmi. İnsan videoya tıklayıp tıklamayacağına buna bakarak karar verir.","Büyük bir başlık ve ekran görüntüsü olan resim."),
("Caption (açıklama metni)","Gönderinin altına yazılan yazı.","Videonun altındaki 'Yeni özellik: ...' cümleleri."),
("Altyazı","Videonun üzerinde konuşulanları gösteren yazı. Çoğu insan sesi kapalı izler; altyazı olmazsa videoyu anlamaz.","Konuşulan her cümle ekranın altında yazılı çıkar."),
("CTA (harekete geçirme)","Paylaşımın sonunda izleyiciden istenen şey.","'Ücretsiz hesap makinesini dene: simpletradejournal.io/tools'"),
("Filigran","Başka bir uygulamanın videonun köşesine koyduğu logo (örneğin TikTok'un logosu). Başka platforma yüklerken görünmemeli.","Bu yüzden her zaman ORİJİNAL dosyayı yükleriz, indirilmiş olanı değil."),
("Sabitlenmiş (pinned)","Bir yorumun ya da mesajın en üstte kalması.","YouTube'da videonun altında en üstte duran bağlantı yorumu."),
("Hashtag","# işaretiyle başlayan etiket. Gönderiyi bulunabilir yapar.","#TradingJournal"),
("Marka kiti","Renkler, yazı tipleri, logo kuralları. Tüm görseller aynı görünsün diye.","Koyu zemin, altın vurgu, Newsreader başlık."),
]

# (yasak, nasıl yapılır)  — kısa kurallar için YAPMA / YAP örnekleri
RULES = [
("1. Para kazanma vaadi yok",
 "Hiçbir cümle 'bunu kullanırsan kazanırsın' demez. 'Garanti', 'kesin', 'kolay para', 'zengin ol' kelimeleri yasak.",
 "Bu programla ayda %20 kazanırsın.",
 "Bu program işlemlerini kaydeder ve hatalarını görmene yardım eder."),
("2. Alım satım tavsiyesi (sinyal) yok",
 "Hiçbir zaman 'şunu al, şunu sat', 'şu fiyatta gir' demeyiz. Fiyat tahmini de yapmayız.",
 "EURUSD 1.0850'den alın, hedef 1.0950.",
 "Pozisyon büyüklüğünü şöyle hesaplarsın: hesabın x %1'i."),
("3. Örnek rakamları 'örnek' diye yaz",
 "Anlatım için rakam kullanabiliriz ama bunların örnek olduğunu açıkça yazarız. Gerçek bir kişinin hesabını göstermeyiz.",
 "Müşterimiz bu ay 3.000 dolar kazandı.",
 "Örnek hesap: 10.000 dolar, %1 risk = 100 dolar. (Örnektir, tavsiye değildir.)"),
("4. Gerçek kullanıcıyı izinsiz gösterme",
 "Bir müşterinin adını, yüzünü, hesabını ya da ekran görüntüsünü yazılı izni olmadan paylaşmayız. İzin varsa bile kişisel bilgi (e-posta, hesap numarası) gizlenir.",
 "Müşteri Ali'nin hesabının ekran görüntüsünü paylaşmak.",
 "Demo hesapla hazırlanmış bir ekran görüntüsü kullanmak."),
("5. Rakipleri kötüleme, doğru yaz",
 "Rakip ürünleri anarken adil ol, bilgi gerçekse ve güncelse yaz. Hakaret yok.",
 "X ürünü rezil bir ürün.",
 "X ürününde bu özellik var, bizde şu özellik var. İhtiyacına göre seç."),
("6. Giriş bilgileri sır",
 "Hesapların şifresi ve doğrulama kodları yöneticide durur. Şifre kimseye yazılmaz, mesajla gönderilmez, kendi telefonuna kaydedilmez. Giriş gerekiyorsa yöneticiden iste.",
 "Şifreyi WhatsApp'tan göndermek.",
 "Yöneticiden giriş izni istemek."),
("7. Her içerik yayından önce kontrol edilir",
 "Hazırladığın içerik hemen yayınlanmaz. Önce trader danışman bakar (bilgi doğru mu? kural ihlali var mı?). Sonra yönetici onaylar. Onaysız yayın yok.",
 "Hazırladığım videoyu direkt yükledim.",
 "Taslağı danışmana gönderdim, onay gelince yayınladım."),
("8. Sinyal isteyene nazikçe hayır",
 "Yorumlarda ya da mesajlarda 'hangi parite alayım?' diye soranlara aynı nazik cevabı veririz.",
 "Bu hafta EURUSD'yi al.",
 "Teşekkürler! Biz sinyal ya da tavsiye vermiyoruz; kendi işlemlerini kaydedip incelemene yardım ediyoruz."),
("9. Hata yaparsan",
 "Yanlış bir şey yayınladıysan paniğe kapılma: gönderiyi hemen sil ya da gizle, yöneticiye hemen haber ver. Saklanan hata, büyür.",
 "Fark ettim ama kimseye söylemedim.",
 "Yanlış rakamı fark ettim, gönderiyi sildim, yöneticiye yazdım."),
]

TOOLS = [
("Canva","Kart, karusel, kapak, thumbnail ve poster tasarımı. Marka rengi ve yazı tipleri hazır girilir (bkz. marka kiti)."),
("Ekran kaydı (Mac: Cmd + Shift + 5)","Programın nasıl kullanıldığını gösteren videolar için. Mac'te Cmd+Shift+5 tuşlarına bas, 'Tüm ekranı kaydet'i seç."),
("Video kurgu programı (örneğin CapCut)","Kesme, birleştirme, altyazı ekleme. Otomatik altyazı özelliği vardır; mutlaka okunup düzeltilir."),
("Telefon (dikey çekim)","Telefonu dik tut (dikey, 9:16). Işık yeterli olsun, ses net olsun."),
("Yazı için: Word ya da Google Docs","Blog yazısı ve metin taslakları. Taslak geliştiriciye teslim edilir; web sitesine yayını geliştirici yapar."),
("Paylaşım takvimi","docs/content-calendar.md dosyası: hangi gün ne paylaşılacak. Her sabah buna bak."),
("Hesap makineleri","Sitede: simpletradejournal.io/tools. İçerik hazırlarken rakamları buradan hesapla; aracın verdiği sonucu kullan."),
]

WORKFLOW = [
("1. Fikir","Takvimde o gün hangi konu yazıyorsa onu al. Takvim yoksa yöneticiye sor."),
("2. Taslak","Metni, videoyu ya da kartı hazırla. Dosyaya tarih ve konu yaz: 2026-10-05_risk-odul_x.png"),
("3. Kendi kontrolün","Aşağıdaki 'Yayından önce' listesini işaretle."),
("4. Danışman kontrolü","Trader danışman bilgiyi ve kuralları kontrol eder. Düzeltme isterse yap."),
("5. Yönetici onayı","Yönetici 'yayınla' der. Bunu duymadan yayınlama."),
("6. Yayın","İlgili kanallara yükle (sonraki bölümlerde adım adım yazıyor)."),
("7. Yorumlar","Yayından sonra ilk saatlerde ve gün içinde yorumlara cevap ver."),
("8. Kayıt","Takvimde 'yayınlandı' diye işaretle. Hangi kanalda ne zaman, bir satır."),
]

PRE_PUBLISH = [
"Yazıda ya da videoda kazanç vaadi, 'garanti', 'kesin' gibi kelime yok.",
"Alım satım tavsiyesi ya da fiyat tahmini yok.",
"Rakamlar örnek hesap ve 'örnek' diye işaretli.",
"Gerçek bir kişinin adı, yüzü, ekran görüntüsü yok (yazılı izin yoksa).",
"Yazım hatası yok. Metni sesli oku.",
"Videoda altyazı var ve doğru.",
"Marka renkleri ve yazı tipi doğru (koyu zemin, altın vurgu, STJ logosu).",
"Bağlantı çalışıyor (tıkla ve dene).",
"Başka platformun logosu (filigran) videoda görünmüyor.",
"Danışman onayı geldi. Yönetici onayı geldi.",
"Metinde fiyat yok (Pro şu an satın alınamıyor; fiyat soran olursa Ücretsiz plan ve 3 günlük deneme anlatılır).",
]
