# Platform rehberi (yeni çalışan için). alanlar: ad, ne, giris, adimlar, ornekler[(baslik, metin, turkce)], yapma, haftalik
def D(ad,ne,giris,adimlar,ornekler,yapma,haftalik): return dict(ad=ad,ne=ne,giris=giris,adimlar=adimlar,ornekler=ornekler,yapma=yapma,haftalik=haftalik)
LOGIN="Giriş bilgisi yöneticidedir (şifre yöneticisinde durur). Şifreyi kendi telefonuna ya da bilgisayarına kaydetme, kimseye yazma. İhtiyacın olunca yöneticiden iste; doğrulama kodunu da yönetici verir."

PG=[
D("Web sitesi",
 "Evimiz: simpletradejournal.io. Bütün kanallar buraya bağlanır. İnsanlar Google'da arar, yazıyı okur, aracı dener, kayıt olur. Burada yayınlanan her şey kalıcıdır.",
 "Çalışanlar siteye doğrudan yazı eklemez. Hazırladığını geliştiriciye teslim edersin; yayınlamayı geliştirici yapar.",
 ["Yazıyı bir belge dosyasında (Word ya da Google Docs) hazırla.","Başlık, 1 cümlelik özet, ana metin, 'journal'da nasıl görürsün' bölümü, 3 sık sorulan soru ve ilgili bağlantıları ekle.","Kapak görselini hazırla (1280x720).","Danışman ve yönetici onayından sonra hepsini geliştiriciye gönder.","Geliştirici yayınlayınca bağlantıyı al, test et ve diğer kanallarda duyur."],
 [("Teslim paketi örneği","Başlık: Başabaş win rate nasıl hesaplanır?\nÖzet: Tek formülle yöntemin kârda olup olmadığını öğren.\nİlgili: /tools/risk-reward-calculator, /blog/expectancy-and-profit-factor\nKapak: basabas-win-rate-kapak.png","(Bu, geliştiriciye gönderilen bilgilerin bir örneğidir.)")],
 ["Siteye kendin bir şey yüklemeye çalışma.","Danışman onayı olmadan teslim etme.","Gerçek müşteri bilgisi koyma."],
 ["1 yazı teslim et.","Yayınlanan yazının bağlantılarını tıklayıp dene.","Yeni yazıyı kanallarda duyur."]),

D("Instagram",
 "Görsel vitrin. Kartlar, kısa videolar ve günlük hikâyeler. İnsanlar bizi burada tanır.",
 "Hesap: @simpletradejournal. "+LOGIN,
 ["KARUSEL: Instagram uygulamasını aç, alt ortadaki + işaretine bas, 'Gönderi'yi seç. Birden fazla resim seç (üst köşedeki kare simgesi), sırayı kontrol et, 'İleri'ye bas. Açıklamayı yaz. 'Paylaş'a bas.","REELS: + → 'Reels' → videoyu seç → 'İleri' → kapak seç → açıklamayı yaz → 'Paylaş'. (Reels en çok 3 dakika olabilir; biz 30-60 saniye yapıyoruz. Hikâye videosu en çok 60 saniyedir.)","STORY: + → 'Hikaye' → resim ya da video seç. Bağlantı koymak için üstteki çıkartma simgesine bas → 'Bağlantı' → adresi yaz → 'Bitti' → 'Hikayen'.","Gönderinin içine bağlantı koyulmaz (tıklanmaz). Bağlantıyı hep story'de ya da hesap biyografisinde ver ve gönderide 'bağlantı biyografide' yaz.","Yayından sonra yorumlara cevap ver."],
 [("Karusel açıklaması","Position sizing in 5 steps. Save this for the next time you open a trade. Free calculator: link in bio. (Example only, not advice.)","Pozisyon büyüklüğü 5 adımda. Bir sonraki işlemde bakmak için kaydet. Ücretsiz hesap makinesi: biyografideki bağlantı. (Yalnız örnektir, tavsiye değildir.)"),
  ("Reels açıklaması","R-multiple in 30 seconds. One number to compare every trade. Free tools: link in bio.","30 saniyede R-multiple. Her işlemi karşılaştıran tek sayı. Ücretsiz araçlar: biyografide."),
  ("Story metni","Today's rule: after a loss, wait 15 minutes before the next trade.","Bugünün kuralı: kayıptan sonra bir sonraki işlemden önce 15 dakika bekle.")],
 ["Gönderiye bağlantı yapıştırma (tıklanmaz).","Başka uygulamanın logolu videosunu yükleme.","Gerçek müşterinin ekran görüntüsünü paylaşma.","Satış ısrarı yapma."],
 ["2 karusel yayınla.","3 Reels yayınla.","Her gün 3-5 story paylaş.","Yorumlara cevap ver.","Ayda 1 canlı yayını planla."]),

D("X (Twitter)",
 "Trader'ların hızlı sohbet ettiği yer. Kısa ipuçları, duyurular, yardım yanıtları.",
 "Hesap: @SimpleTradeJrnl. "+LOGIN,
 ["Bilgisayarda sol menüdeki 'Post' düğmesine bas. Telefonda sağ alttaki + düğmesine bas ve 'Post'u seç.","Metni yaz (en çok 280 karakter; daha uzun gerekiyorsa thread yap).","Görsel ya da video için alttaki resim simgesine bas ve dosyayı seç. Videoya altyazı eklenmiş olmalı.","Thread için metin kutusunun altındaki '+' işaretine bas ve sıradaki tweeti yaz.","'Post' düğmesine bas.","Bağlantı varsa metnin sonuna koy."],
 [("Günlük ipucu","Position size should be decided before the entry price. Free calculator: simpletradejournal.io/tools/position-size-calculator","Pozisyon büyüklüğü, giriş fiyatından önce belli olmalı. Ücretsiz hesap makinesi: ..."),
  ("Video tweeti","Spot the mistake. Three trades in six minutes, each bigger than the last. That is revenge trading.","Hatayı bul. Altı dakikada üç işlem, her biri öncekinden büyük. Buna intikam işlemi denir."),
  ("Anket","How many trades do you take in a day? A) 1-2 B) 3-5 C) 6-10 D) 10+","Günde kaç işlem açıyorsun?")],
 ["Tavsiye ya da fiyat tahmini yazma.","10 hashtag koyma (en çok 1-2).","Tartışmalara kızgın cevap verme."],
 ["Her gün 1-2 paylaşım yap.","2-3 video paylaş.","1 thread ve 1 anket yap.","Yardım gereken sorulara cevap ver."]),

D("YouTube",
 "Eğitim ve kurulum videolarının evi. Google aramasında da çıkar. Kanal henüz açılmadı: admin@ hesabı 30 günlük olunca (11 Ekim'den sonra) açılacak.",
 "Kanal açılınca: adı Simple Trading Journal, adres @simpletradejournal. "+LOGIN,
 ["Bilgisayarda youtube.com'a gir. Sağ üstteki 'Oluştur' → 'Video yükle'.","Dosyayı seç. Başlığı yaz (anahtar kelimeli, kısa).","Açıklamayı yaz (şablon aşağıda).","Kapak resmini (thumbnail) yükle.","'Hayır, çocuklar için değil' seç. Oynatma listesini seç.","Altyazıyı yükle ya da otomatik altyazıyı kontrol et.","Görünürlükte 'Herkese açık'ı seç, sonra 'Kaydet' ya da 'Yayınla' düğmesine bas (ekranda hangisi yazıyorsa).","Videonun altına sabitlenmiş yorum yaz (araç bağlantısı).","60 saniyeden kısa dikey video aynı yoldan yüklenir ve Shorts olarak yayınlanır."],
 [("Açıklama şablonu","In this video you learn how to keep a trading journal in 3 simple steps.\n\nFree tools: simpletradejournal.io/tools\nFree account: simpletradejournal.io\n\n0:00 Intro\n0:15 Step 1\n3:00 Step 2\n\nThis video is for education only and is not financial advice.","Bu videoda işlem günlüğünü 3 basit adımda tutmayı öğrenirsin. Ücretsiz araçlar ve hesap bağlantıları. Bölüm zamanları. Bu video yalnız eğitim içindir, yatırım tavsiyesi değildir."),
  ("Sabit yorum","Free position size calculator: simpletradejournal.io/tools/position-size-calculator","Ücretsiz pozisyon büyüklüğü hesap makinesi.")],
 ["Kazanç gösteren ekran kaydı yükleme.","Altyazıyı kontrol etmeden yayınlama.","'Garanti', 'kesin kazanç' gibi sözler.","Başlığı yanıltıcı yazma (örneğin 'ŞOK')."],
 ["1 uzun video yükle.","2-3 Shorts yükle.","Yorumlara cevap ver.","Oynatma listelerini kontrol et."]),

D("TikTok",
 "Kısa ve hızlı videoların kanalı. Genç trader'lara ulaşır. Reels ve Shorts ile aynı videolar yüklenir.",
 "Hesap şu an açık, kullanıcı adı 30 Ekim'den sonra düzeltilecek. "+LOGIN,
 ["TikTok uygulamasını aç, alt ortadaki + işaretine bas.","Sağ alttaki 'Yükle' (galeri) ile hazır videoyu seç.","'İleri'ye bas. Altyazı ekli videoysa tekrar eklemene gerek yok.","Açıklamayı yaz (1-2 cümle + en çok 3 hashtag).","Gizlilik: 'Herkes'.","'Paylaş'a bas."],
 [("Açıklama","Spot the mistake in 3 trades. Would you have stopped earlier? #tradingjournal #riskmanagement","3 işlemde hatayı bul. Sen daha erken durur muydun?")],
 ["Başka platformun logolu videosunu yükleme.","Para ya da kâr gösteren ekran görüntüsü paylaşma.","Trend sesi kullanırken telif ve konu uyumunu kontrol et."],
 ["3 video yükle.","Yorumlara cevap ver (gerekirse video ile).","İstatistiklere bak: hangi video çok izlendi?"]),

D("Telegram",
 "Duyuru kanalı. Üyeler bildirim alır, bizim yeni yazı ve araçlarımızı doğrudan görür.",
 "Kanal: t.me/simpletradejournal. "+LOGIN,
 ["Telegram'ı aç, kanalı bul (yönetici hesabıyla).","Alttaki mesaj kutusuna metni yaz.","Resim ya da video için soldaki ataş simgesine bas, dosyayı seç. PDF'i de aynı şekilde yükleyebilirsin.","Gönder simgesine bas.","Önemli bir mesajı sabitlemek için mesaja basılı tut → 'Sabitle'.","Anket için ataş menüsünde 'Anket' seç."],
 [("Günlük kural","Today's rule: if you hit your daily loss limit, the day is over.","Bugünün kuralı: günlük kayıp limitine ulaştıysan gün biter."),
  ("Yeni yazı","New article: R-multiple, explained with one simple example. Read: simpletradejournal.io/blog/r-multiple-explained","Yeni yazı: Tek bir basit örnekle R-multiple.")],
 ["Günde 3'ten fazla paylaşım yapma (üyeyi rahatsız eder).","Sinyal paylaşma.","Gereksiz tekrar yapma."],
 ["Her gün 1 paylaşım yap.","Pazar günü haftalık özeti gönder.","Anket yap."]),

D("Facebook",
 "Meta (Instagram ile aynı şirket) reklam hesabı için gerekli sayfamız. Çoğu içerik Instagram'dan kendiliğinden gelir; ek çaba harcamayız.",
 "Sayfa: facebook.com/simpletradejournalapp. Sayfa kişisel hesaptan yönetilir; yönetici bunu halleder. "+LOGIN,
 ["Instagram paylaşımları otomatik Facebook'a yansır (bu ayarı yönetici bir kez yapar).","Ek paylaşım gerekirse yönetici sayfa adına geçer: sağ üstte profil resmi → sayfa adı.","'Ne düşünüyorsun?' kutusuna metni yaz, 'Fotoğraf/video' ile dosya ekle, 'Paylaş'.","Etkinlik: sayfada 'Etkinlik oluştur'."],
 [("Önemli içerik","New on Simple Trading Journal: a free risk/reward calculator. simpletradejournal.io/tools","Yeni: ücretsiz risk/ödül hesap makinesi.")],
 ["Sayfayı kapatma ya da silme.","Facebook için ayrı içerik üretmeye zaman harcama."],
 ["Instagram'dan yansıyanları kontrol et.","Ayda 1 sayfa bilgilerini kontrol et."]),

D("LinkedIn",
 "İş dünyası ağı. Profesyonel trader'lar, prop firma ve broker çalışanları. Dil daha ciddi, veri ve disiplin odaklı.",
 "Sayfa: linkedin.com/company/simpletradejournal. Sayfa kişisel hesaptan yönetilir; yönetici bunu halleder. "+LOGIN,
 ["Şirket sayfasını yönetici olarak aç.","'Gönderi başlat'a bas.","Metni yaz (ilk iki satır en önemlisi: orada kes görünür).","Resim/video için medya simgesi; PDF karusel için 'Belge ekle' ve PDF'i seç.","'Gönderi'ye bas."],
 [("PDF karusel","Five checks before a prop firm daily loss limit. Swipe through the PDF. Education only, not financial advice.","Günlük kayıp limitinden önce beş kontrol. PDF'i kaydırarak oku. Yalnız eğitim içindir."),
  ("Kısa video","Prop firm daily loss limit, explained in 40 seconds.","Prop firma günlük kayıp limiti, 40 saniyede.")],
 ["Hashtag'i 3'ten fazla yazma.","Eğlence ya da trend videosu paylaşma.","Kişisel hesaptan şirket adına ciddi karar bildirme."],
 ["2 gönderi paylaş.","Haftada 1 PDF karusel ya da kısa video yükle."]),

D("Reddit",
 "Konu bazlı topluluk forumu. Reklam yapanı hemen banlarlar. Biz burada satıcı değil, yardımcı insan rolündeyiz. İlk 1-2 ay yalnız yorum yaz.",
 "Hesap: u/simpletradejournal. "+LOGIN,
 ["Reddit'te ilgili konu grubunu bul (r/Forex, r/Daytrading).","Önce 'Rules' (kurallar) bölümünü oku.","Soruları ara: 'journal', 'position size'.","Gönderiyi aç, 'Yorum ekle'ye bas, yardımcı cevabı yaz, 'Yorum yap'a bas.","Bağlantı koyma (ya da en çok bir tane ve cevap tek başına yeterli olsun)."],
 [("Yardım yorumu","One simple way is to decide first how much you are willing to lose, say 1% of your account. On a 10,000 account that is 100. Then divide that by your stop distance in money per lot. This is only an example, not advice.","Basit bir yol: önce ne kadar kaybetmeyi göze aldığına karar ver, örneğin hesabın %1'i. 10.000 dolarlık hesapta bu 100 dolar. Sonra bunu, lot başına para cinsinden stop mesafene böl. Yalnız örnektir.")],
 ["Yeni hesapla bağlantı koyma.","'Bizim ürünü dene' deme.","Aynı yorumu birçok yere kopyalama.","Tartışmaya girme."],
 ["Haftada 3 yardımcı yorum yaz.","Kuralları ayda bir tekrar oku."]),

D("Discord",
 "Topluluk sunucumuz. Kullanıcılar burada sohbet eder, soru sorar, geri bildirim verir.",
 "Sunucu: Simple Trading Journal (davet bağlantısı sitenin alt bilgisinde). "+LOGIN,
 ["Sol listeden kanalı seç (announcements, general, support, feedback).","Alttaki mesaj kutusuna yaz.","Dosya için kutunun solundaki + işaretine bas → 'Dosya yükle'.","Anket için + menüsünde anket seçeneği varsa onu kullan.","Enter'a bas.","announcements ve welcome kanallarına yalnız yönetici yazabilir."],
 [("Haftalık soru","Weekly question: what was your biggest mistake this week? No wrong answers, we learn together.","Haftanın sorusu: bu haftaki en büyük hatan neydi? Yanlış cevap yok, birlikte öğreniriz."),
  ("Duyuru","New: a free risk/reward calculator. simpletradejournal.io/tools","Yeni: ücretsiz risk/ödül hesap makinesi.")],
 ["Sunucuyu boş bırakma: haftada en az 2 mesaj.","Sinyal isteyen birine sinyal verme (nazikçe hayır de).","Kullanıcı verisini (e-posta, hesap) herkese açık yerde paylaşma."],
 ["1 duyuru yaz.","1 tartışma sorusu sor.","support kanalına 24 saat içinde cevap ver."]),
]
