# Her içerik türü için çalışan kartı.
# alanlar: no, ad, nedir, kim, siklik, hazirlik, adimlar, ornek, yapma
def C(no,ad,nedir,kim,siklik,hazirlik,adimlar,ornek,yapma):
    return dict(no=no,ad=ad,nedir=nedir,kim=kim,siklik=siklik,hazirlik=hazirlik,adimlar=adimlar,ornek=ornek,yapma=yapma)

T=[
C(1,"Uzun eğitim videosu (8-15 dakika)",
 "Bir konuyu baştan sona anlatan uzun video. Ekranda program görünür, sen anlatırsın. Örneğin 'trading journal nasıl tutulur?'. Bir kez çekilir, YouTube'da uzun süre izlenir. Bu videodan sonra kısa videolar çıkarılır.",
 "Video yapımcısı çeker ve kurgular; danışman bilgiyi kontrol eder.","Haftada 1.",
 "Ekran kaydı, mikrofon (sessiz bir oda), kurgu programı, senaryo.",
 ["Konuyu seç (takvimden). Tek konu: tek video.","Senaryoyu yaz. Üç parça: (a) 15 saniyede 'bu videoda ne öğreneceksin', (b) 3-5 adım halinde anlatım, (c) özet ve çağrı.","Örnek (demo) veriyi hazırla. Gerçek kullanıcı verisi kullanma.","Ekran kaydını al: Cmd+Shift+5. Sakin, yavaş konuş. Hata yaparsan durma, cümleyi baştan söyle; kurguda keseriz.","Kurgula: boşlukları ve hataları kes. Altyazı ekle ve oku, hataları düzelt.","Thumbnail (kapak) hazırla (tür 11).","Danışmana gönder, düzeltmeleri yap, yönetici onayı al.","YouTube'a yükle (YouTube bölümüne bak). Sonra 3-5 kısa kesit çıkar (tür 3)."],
 "Başlık: 'Trading journal nasıl tutulur? 10 dakikada adım adım'\nSenaryo:\n0:00-0:15  'Bu videoda bir işlem günlüğünü nasıl tutacağını öğreneceksin: neyi yazacağını, ne zaman yazacağını ve neden yazacağını.'\n0:15-3:00  Adım 1: İşlemi yaz (giriş fiyatı, çıkış fiyatı, neden girdin). Ekranda örnek bir satır göster.\n3:00-6:00  Adım 2: Duygunu yaz (acele ettin mi? korktun mu?).\n6:00-8:00  Adım 3: Haftada bir bak ve tekrar eden hatayı bul.\n8:00-9:30  Özet: 3 adımı tekrar söyle.\n9:30-10:00 'Ücretsiz hesap açmak için bağlantı açıklamada.' (Kazanç vaadi yok.)",
 ["Kazanç vaadi ya da 'bunu yaparsan kazanırsın' deme.","Gerçek bir hesabın ekran görüntüsünü gösterme.","Sesi bozuk ya da arka planda gürültü varken yükleme.","Altyazıyı kontrol etmeden yükleme."]),

C(2,"Kurulum ve ürün turu videosu",
 "Programın nasıl kurulacağını ya da bir özelliğin nasıl kullanılacağını gösteren ekran kaydı. 'Bu butona bas, şuraya yaz' gibi. Müşteri takıldığı zaman bu videoya bakar.",
 "Video yapımcısı çeker; danışman kontrol eder.","Yeni özellik çıktıkça; ayda en az 2.",
 "Ekran kaydı, demo hesap, kurgu programı.",
 ["Konuyu seç. Örnek: 'MT5'ten otomatik senkron nasıl kurulur?'.","Önce kendin dene, adımları kâğıda yaz (1, 2, 3, ...).","Ekran kaydını başlat. Her adımı yavaşça yap, imleci (fare okunu) sabit tut. Her adımın başında ne yaptığını söyle.","Kurgula: bekleme anlarını kes. Önemli düğmeleri ok ya da çerçeveyle işaretle.","Altyazı ekle. Video 60 saniyeden uzunsa 'bölüm' başlıkları ekle (0:00 Giriş, 0:20 Kurulum...).","Danışman ve yönetici onayından sonra yükle. Sitede yardım sayfasına eklemek için geliştiriciye bildir."],
 "Başlık: 'MT5'ten otomatik senkron: kurulum 5 adımda'\nAdımlar (ekranda sırayla göster):\n1) Siteye gir ve giriş yap.\n2) MetaTrader ekranını göster.\n3) Siteden verilen anahtarı kopyala.\n4) MetaTrader'da eklentiye yapıştır.\n5) 'Bağlan' de, işlemlerin sitede göründüğünü göster.\nKapanış: 'Takıldığın yer olursa support kanalına yaz.'",
 ["Adımları hızlı geçme.","Kendi gerçek hesap anahtarını (şifre gibi) ekranda gösterme: yalnız demo anahtar kullan.","Eski ekranları gösterme: program güncellendiyse yeniden çek."]),

C(3,"Kısa ipucu videosu (15-60 saniye)",
 "Tek bir fikri bir dakikadan kısa anlatan dikey video. Instagram Reels, TikTok, YouTube Shorts, X, Facebook, LinkedIn'e aynı video yüklenir.",
 "Video yapımcısı.","Haftada 3.",
 "Telefon (dikey), kurgu programı, altyazı.",
 ["Tek fikir seç: 'R-multiple nedir?', 'Pozisyon büyüklüğü nasıl hesaplanır?'.","Cümleyi 3 parçaya böl: (a) soru ya da şaşırtıcı bir söz (ilk 3 saniye), (b) kısa açıklama, (c) tek cümlelik özet.","Telefonu DİK tut, ışığa bak, net konuş. Ekran kaydı ya da kart da gösterebilirsin.","Kurgula: gereksiz saniyeleri kes. İlk 3 saniyede konu belli olsun.","Altyazıyı ekle ve oku.","Danışman/yönetici onayı. Sonra ORİJİNAL (filigransız) dosyayı tüm kanallara yükle. Her kanal için başlığı o kanala göre yaz."],
 "R-multiple 30 saniyede (örnek senaryo)\n0:00 'Bir işlemde 100 dolar riske ettin. 200 dolar kazandın. Bu kaç R? İki. Artı iki R.'\n0:08 'R, kazancını ya da kaybını riske bölerek bulursun.'\n0:15 'Kaybettiysen, 100 dolar kaybettin, eksi bir R.'\n0:22 'Böylece küçük işlemle büyük işlemi aynı ölçüyle kıyaslarsın.'\n0:28 'Ücretsiz hesap makinesi bağlantıda.'",
 ["60 saniyeden uzun yapma.","Altyazısız yükleme.","Videoya başka uygulamanın logosu (filigran) girmesin.","Birden fazla konuyu tek videoya doldurma."]),

C(4,"Hata analizi videosu",
 "Örnek (demo) bir işlemde yapılan bir hatayı gösterip 'bu neden hata?' diye anlatan video. İzleyen kendi hatasını fark eder.",
 "Video yapımcısı; danışman bilgiyi kontrol eder.","Haftada 1-2.",
 "Ekran kaydı, demo işlem verisi, kurgu programı.",
 ["Bir hata seç: intikam işlemi, aşırı işlem, çok büyük pozisyon, stop koymamak.","Demo bir işlem listesi hazırla (gerçek değil).","Kaydı al: önce listeyi göster, izleyiciye sor 'Hatayı buldun mu?', 3 saniye bekle, sonra göster.","Hatayı bir cümleyle adlandır ve neden sorun olduğunu açıkla.","Çözümü bir cümleyle söyle (tavsiye değil; kural örneği): 'Kayıptan sonra 15 dakika ara ver.'","Altyazı, kurgu, onay, yayın."],
 "Başlık: 'Bu işlemde hatayı bul'\nEkranda (demo): 09:10 işlem -50 dolar. 09:12 işlem -80 dolar. 09:14 işlem -120 dolar.\nSöz: 'Üç dakikada üç işlem, her biri öncekinden büyük. Bu intikam işlemi: kaybı hemen geri almaya çalışıyorsun. Çözüm: kayıptan sonra dur, nefes al, planına dön.'",
 ["Gerçek bir kullanıcının işlemini kullanma.","'Şunu yapmazsan kazanırsın' deme.","İzleyiciyi küçümseme ya da kınama."]),

C(5,"Prop firma kural rehberi (video)",
 "Prop firmanın kurallarını (günlük kayıp, toplam kayıp, drawdown) basitçe anlatan video. Ardından 'bunu programda nasıl takip edersin?' gösterilir.",
 "Video yapımcısı; danışman kuralları kontrol eder.","Ayda 1-2 (yeni firma ya da kural değişince).",
 "Firmanın resmi kural sayfası, ekran kaydı.",
 ["Firmanın resmi kural sayfasını aç. Kuralları kendi cümlenle yaz. Tarihi not et.","Danışmana doğrulat. Kural değişmiş olabilir.","Örnek hesapla anlat: 10.000 dolar hesap, günlük kayıp %5 = 500 dolar.","Programda limiti nasıl takip ettiğini göster.","Videoya ve açıklamaya 'kurallar değişebilir, resmi sayfayı kontrol et' notu ve tarih yaz.","Altyazı, onay, yayın."],
 "Başlık: 'Günlük kayıp limitini nasıl takip edersin?'\nSöz: 'Örnek: hesap 10.000 dolar, günlük kayıp limiti yüzde 5, yani 500 dolar. Bugün 300 dolar kaybettiysen limite 200 dolar kaldı. Programda bu tek bakışta görünür.'\nAltyazı notu: 'Kurallar değişebilir; resmi sayfayı kontrol et. Tarih: 1 Ekim 2026.'",
 ["Kuralı ezberden anlatma: resmi sayfadan kontrol et.","Firmayı övme ya da kötüleme.","Tarihsiz yayınlama."]),

C(6,"Canlı yayın ve soru-cevap",
 "Ayda bir, topluluğun sorularını canlı yanıtlama. Kaydı sonra kısa videolara bölünür.",
 "Sosyal medya yöneticisi + trader danışman (sorulara cevap verir).","Ayda 1.",
 "Instagram ya da YouTube canlı yayın, sessiz oda, soruların listesi.",
 ["Tarih ve saat belirle; 1 hafta önce duyur (story, X, Telegram, Discord).","Sorular topla: story'de 'soru kutusu' aç.","Soruları listele, tehlikeli olanları (sinyal isteyenler) ayır.","Yayın günü: bağlantıyı test et, sesi test et.","Canlı: her soruyu oku, danışman cevaplasın. Sinyal soran olursa nazikçe hayır de.","Bittikten sonra kaydı kaydet, yönetici onayından sonra YouTube'a yükle."],
 "Duyuru metni: 'Ayın soru-cevap yayını 18 Ekim Pazar 20:00. Sorularını story'e ya da Discord'a yaz. Sinyal ve tavsiye sormayın; biz yalnız işlem takibi ve disiplin konuşuruz.'",
 ["Canlıda fiyat tahmini yapma.","Kimsenin kişisel hesabını göstermeye çalışma.","Yayını izinsiz bölme ya da kırpma yapıp yanıltıcı yayma."]),

C(7,"Karusel (5-7 kart)",
 "Kaydırmalı gönderi: bir konuyu 5-7 görselle anlatır. Instagram'da karusel, LinkedIn'de PDF karusel olarak yüklenir.",
 "Grafik tasarımcı; yazar metni verir.","Haftada 2.",
 "Canva, marka kiti, metin.",
 ["Konuyu seç. Başlığı yaz: 'Pozisyon büyüklüğü 5 adımda'.","Metni yaz: kart başına 1-2 cümle. Kart 1: başlık (merak). Kart 2-5: adımlar. Kart 6: özet. Kart 7: çağrı.","Canva'da 1080x1350 boyutunda boş tasarım aç.","Marka kiti: koyu zemin (#08080c), yazı (#F4F2EC), vurgu (altın #f0b429). Başlık yazısı Newsreader, metin Inter.","Her karta metni yerleştir, logoyu sağ üste koy.","Tüm kartlara bak: hepsi okunuyor mu? Yazım hatası var mı?","PNG olarak indir. LinkedIn için aynı kartları PDF indir. Onaya gönder."],
 "Kart 1: 'Pozisyon büyüklüğü 5 adımda'\nKart 2: '1. Hesabını yaz. Örnek: 10.000 dolar.'\nKart 3: '2. Riskini seç. Örnek: %1 = 100 dolar.'\nKart 4: '3. Stop mesafesini belirle. Örnek: 20 pip.'\nKart 5: '4. Hesapla: 100 / (20 x 10) = 0,5 lot.'\nKart 6: 'Özet: önce risk, sonra büyüklük.'\nKart 7: 'Ücretsiz hesap makinesi: bağlantı biyografide. (Örnektir, tavsiye değildir.)'",
 ["Her karta çok yazı doldurma: bir kartta bir fikir.","Yazı tipini ya da rengi değiştirme.","Örnek rakamı 'örnek' diye yazmayı unutma."]),

C(8,"Kural kartı (tek görsel)",
 "Tek bir kuralı gösteren tek bir görsel. En hızlı hazırlanan ve en çok paylaşılan içerik.",
 "Grafik tasarımcı.","Haftada 3-5.",
 "Canva, marka kiti.",
 ["Bir kural seç. Kısa olsun (en çok 12 kelime).","Canva'da 1080x1080 (kare) aç; X için 1600x900 da hazırla.","Koyu zemin, kuralı büyük yaz, kritik 2-3 kelimeyi altın renkle yaz.","Sol üste STJ logosu, altta simpletradejournal.io.","PNG indir. Onaya gönder."],
 "Kart metni: 'Kayıptan sonra ilk işlemi yazmadan açma.' (Vurgu: 'yazmadan açma'.)\nAltına caption: 'Bir işlem açmadan önce 10 saniye dur ve nedenini bir cümleyle yaz.'",
 ["Tavsiye gibi yazma ('şunu al').","12 kelimeden uzun yazma.","Aynı kartı üst üste paylaşma."]),

C(9,"İnfografik (formül/şema görseli)",
 "Bir formülü ya da kavramı çizimle anlatan görsel.",
 "Grafik tasarımcı; yazar bilgiyi verir, danışman doğrular.","Ayda 2-3.",
 "Canva.",
 ["Konuyu ve formülü yaz. Danışmana doğrulat.","Canva'da 1080x1350 aç.","Formülü büyük yaz, altına 1 örnek rakamla çöz.","Renk: aynı marka kiti. Altın yalnız vurgu için.","PNG indir, onaya gönder."],
 "Başlık: 'Beklenti formülü'\nGörsel: 'Beklenti = (kazanma oranı x ortalama kazanç) - (kaybetme oranı x ortalama kayıp)'\nÖrnek: '0,40 x 2R - 0,60 x 1R = +0,2R. Örnektir.'",
 ["Formülü danışmana göstermeden yayınlama.","Örnek rakamı gerçekmiş gibi sunma."]),

C(10,"Ürün güncelleme görseli",
 "Siteye yeni bir özellik eklendiğinde, onu duyuran görsel (ekran görüntüsü + bir cümle).",
 "Grafik tasarımcı; geliştirici özelliği anlatır.","Yeni özellik çıktıkça.",
 "Yeni özelliğin ekran görüntüsü, Canva.",
 ["Geliştiriciden: ne eklendi, kime yarar? Bir cümle yaz.","Siteyi aç, demo hesapla ekran görüntüsünü al (gerçek bilgi görünmesin).","Canva şablonunda 'Yeni:' başlığı + ekran görüntüsü + bir cümle.","PNG indir, onaya gönder.","Aynı gün: Instagram, X, Telegram, LinkedIn, Discord; değişiklik günlüğü için geliştiriciye bildir."],
 "Kart: 'Yeni: prop firma limit göstergesi'\nCaption: 'Günlük kayıp limitine ne kadar yaklaştığını artık tek bakışta görüyorsun. Prop firma hesabı olanlar için.'",
 ["Henüz yayında olmayan özelliği duyurma.","Ekran görüntüsünde gerçek kullanıcı bilgisi bırakma."]),

C(11,"Kapak (thumbnail) ve görseller",
 "YouTube video kapağı, blog kapağı, hesap kapakları.",
 "Grafik tasarımcı.","Her video ve yazı için 1.",
 "Canva.",
 ["Video başlığını al.","Canva'da 1280x720 (YouTube kapağı) aç.","Koyu zemin, başlığı 3-5 kelimeyle büyük yaz, ekran görüntüsü ya da sade ikon koy.","Yazı küçültüldüğünde okunuyor mu? (kapağı telefonda küçük göster, kontrol et)","PNG indir ve videoya yükle."],
 "Kapak yazısı: 'R-MULTIPLE NEDİR?' (altın: 'R-MULTIPLE')",
 ["Çok yazı koyma.","Yalan söz yazma (örneğin 'ŞOK').","Başka birinin fotoğrafını izinsiz kullanma."]),

C(12,"İndirilebilir şablon (PDF)",
 "İndirilip yazdırılabilen ya da doldurulabilen bir sayfa: işlem öncesi kontrol listesi, haftalık gözden geçirme sayfası. Sitede indirilir, kişiden e-posta istenir.",
 "Grafik tasarımcı + yazar; geliştirici siteye koyar.","Ayda 1 yeni şablon.",
 "Canva, PDF çıktısı.",
 ["Şablonu planla: 1 sayfa, doldurulabilir.","Canva'da A4 aç, başlık + tablo/kutucuklar yap.","Altına 'Yatırım tavsiyesi değildir' notu ve site adresi.","PDF olarak indir. Danışmana göster.","Geliştiriciye teslim et (site yükleme). Tanıtımı: Instagram story/biyografi bağlantısı, X'te bağlantı, Telegram ve Discord'a doğrudan PDF."],
 "Şablon: 'İşlem öncesi kontrol listesi'\n[ ] Bu işlemin nedeni ne? [ ] Stop nerede? [ ] Riskim hesabımın yüzde kaçı? [ ] Duygusal mıyım (öfke, korku)? [ ] Planıma uyuyor mu?",
 ["Para kazanma vaadi koyma.","PDF'i Instagram ya da X'e dosya olarak yüklemeye çalışma: bağlantı ver."]),

C(13,"Blog yazısı",
 "Sitede yayınlanan yazı. Google'da aranan sorulara cevap verir. Her yazı bir sorunun cevabıdır.",
 "Yazar; danışman kontrol eder; geliştirici siteye ekler.","Haftada 1.",
 "Metin programı, örnek hesap, ilgili araç bağlantıları.",
 ["Konuyu seç (soru): 'Başabaş win rate nasıl hesaplanır?'","Yazıyı yaz: (a) 3 cümlelik giriş, (b) adım adım anlatım, (c) örnek hesap (örnek diye işaretli), (d) 'journal'da nasıl görürsün', (e) sık sorulan 3 soru, (f) son satır: ücretsiz hesap çağrısı.","Hedef uzunluk: 1.000-1.500 kelime.","Yazıdan en az 2 ilgili sayfaya (araç, başka yazı) bağlantı ver.","Danışmana teslim et, düzeltmeleri yap.","Geliştiriciye teslim et. Yazı yayınlanınca kanallara duyur."],
 "Başlık: 'Başabaş win rate nasıl hesaplanır?'\nGiriş: 'Bir yöntem kârda mı? Bunun cevabı yalnız kazanma oranına değil, kazancın kayba oranına da bağlı. Bu yazıda tek formülle öğreneceksin.'\nÖrnek: 'Risk/ödül 1'e 2 ise, başabaş için yüzde 33,3 kazanma oranı yeter. (Örnek hesaptır, tavsiye değildir.)'",
 ["Başka sitenin yazısını kopyalama.","Her yazıda tek konu.","Bilgiyi danışmana doğrulatmadan gönderme."]),

C(14,"Karşılaştırma yazısı",
 "'X ürününün alternatifi' yazısı: iki ürünü yan yana koyar. Satın almak üzere olanlar bunu arar.",
 "Yazar; danışman/yönetici kontrol eder.","Yeni rakip çıktıkça.",
 "Rakip ürünün resmi fiyat ve özellik sayfası.",
 ["Rakibin resmi sitesinden fiyat ve özellikleri al, tarihini yaz.","Tablo yap: fiyat, MetaTrader senkronu, desteklenen platformlar, disiplin analizi, prop firma takibi.","Rakibin güçlü yanlarını da yaz (adil ol).","Bizim güçlü yanlarımızı yaz ('şu kişi için daha uygun').","Tarihi yaz: 'Bilgiler 1 Ekim 2026 itibarıyladır.'","Onay, geliştiriciye teslim."],
 "Başlık: 'Tradezella alternatifi: Simple Trading Journal ile karşılaştırma'\nTablo satırı: 'MetaTrader otomatik senkron: bizde var (MT4 ve MT5).'",
 ["Rakibi kötüleme.","Eski fiyatı yazma: tarihi kontrol et.","Doğrulanmamış bilgiyi yazma."]),

C(15,"Prop firma / broker sayfası",
 "Her prop firma ya da broker için ayrı sayfa: kuralların özeti ve 'programda nasıl takip edersin?'.",
 "Yazar; danışman kuralları kontrol eder; geliştirici ekler.","Ayda 1-2 yeni sayfa; ayda bir kural kontrolü.",
 "Firmanın resmi kural sayfası.",
 ["Firmanın resmi kural sayfasını aç.","Kuralları kendi cümlenle yaz: günlük kayıp, toplam kayıp, drawdown türü.","'Programda nasıl takip edersin?' bölümünü yaz.","Sayfanın altına 'kurallar değişebilir, resmi sayfayı kontrol et' ve son kontrol tarihi.","Danışman onayı, geliştiriciye teslim."],
 "Başlık: 'FTMO kuralları takip aracı'\nBölüm: 'Günlük kayıp limiti nedir? ... Programda tek bakışta görürsün. Son kontrol: 1 Ekim 2026.'",
 ["Kuralı ezberden yazma.","Tarihsiz bırakma."]),

C(16,"Kısa metin ve thread",
 "X'te günlük ipucu cümlesi ya da art arda bağlı 5-8 tweet (thread). Diğer kanallarda da kısa metin olarak kullanılır.",
 "Yazar / sosyal medya yöneticisi.","Günde 1-2 kısa metin; haftada 1 thread.",
 "Metin programı.",
 ["Bir fikir seç.","Günlük ipucu: tek cümle (en çok 200 karakter).","Thread: ilk tweet merak uyandıran cümle; sonra 4-6 tweet adım adım; son tweet özet ve bağlantı.","Her tweet kendi başına anlaşılır olsun.","Onay, yayın."],
 "Günlük ipucu: 'Pozisyon büyüklüğü, giriş fiyatından önce belli olmalı.'\nThread: 1/6 'Bir intikam işleminin anatomisi.' 2/6 'Önce kayıp gelir.' 3/6 'Sonra acele. ...' 6/6 'Çözüm: kayıptan sonra dur. (Tavsiye değil, disiplin örneği.)'",
 ["Hashtag yığma (en çok 1-2).","Sinyal ya da fiyat tahmini yazma."]),

C(17,"Haftalık bülten",
 "Her hafta e-postayla gönderilen özet: yeni yazılar, yeni araçlar, güncellemeler. Telegram ve LinkedIn'de de özet olarak paylaşılır.",
 "Yazar; yönetici onaylar.","Haftada 1 (pazar).",
 "Haftanın içeriklerinin listesi.",
 ["Haftanın yayınlarını listele.","3-5 madde yaz: her biri başlık + 1 cümle + bağlantı.","Giriş: 2 cümle. Kapanış: 1 cümle.","Onay al. Gönderimi yönetici/geliştirici yapar."],
 "Başlık: 'Bu hafta: R-multiple, yeni hesap makinesi ve bir hata analizi'\n1) 'R-multiple nedir?' (yazı) 2) 'Yeni: risk/ödül hesap makinesi' 3) 'Bu işlemde hatayı bul' (video)",
 ["Aynı içeriği tekrar tekrar koyma.","Uzatma: en çok 5 madde."]),

C(18,"Sözlük, SSS ve yardım sayfası",
 "Terimlerin kısa anlatımı (sözlük) ve sık sorulan soruların cevabı (SSS, yardım). Müşteri takılınca buraya bakar.",
 "Yazar; geliştirici ekler.","Yeni terim ya da sık gelen soru çıktıkça.",
 "Müşteri soruları listesi (support kanalı, iletişim formu).",
 ["Sık sorulan soruyu al.","Cevabı basit yaz: 3-4 cümle.","Gerekirse ekran görüntüsü ekle.","Danışman kontrolü, geliştiriciye teslim.","X'te 'bu haftanın terimi' diye paylaş."],
 "Soru: 'Win rate nedir?'\nCevap: 'Win rate, işlemlerinin yüzde kaçının kârla bittiği. 10 işlemin 4'ü kârlıysa win rate yüzde 40'tır.'",
 ["Karmaşık cümle kurma.","Bilmediğin şeyi yazma: danışmana sor."]),

C(19,"Ücretsiz hesap makineleri",
 "Sitede çalışan küçük araçlar: rakam girersin, sonucu görürsün. Örnek: pozisyon büyüklüğü hesap makinesi. Hesap makinesinin kendisini YAZILIMCI yapar; içerik ekibi o aracı TANITIR.",
 "Geliştirici aracı yapar; içerik ekibi tanıtımı hazırlar.","Yeni araç çıktıkça; ayrıca ara sıra yeniden tanıtım.",
 "Aracı kullanan ekran kaydı ya da ekran görüntüsü.",
 ["Aracı sitede aç (simpletradejournal.io/tools) ve kendin dene.","Örnek bir hesap yap, ekran görüntüsü al.","Tanıtım içeriği: Instagram'da kart ya da kısa video, X'te görsel + bağlantı, YouTube'da 3-5 dakikalık anlatım videosu, Telegram'da duyuru.","Metinde mutlaka 'ücretsiz' ve araç bağlantısı yaz.","Onay ve yayın."],
 "X metni: 'Free position size calculator: enter your account, risk % and stop distance, get the lot size. simpletradejournal.io/tools/position-size-calculator'\n(Türkçesi: Ücretsiz pozisyon büyüklüğü hesap makinesi: hesabını, riskini ve stop mesafeni gir, lot büyüklüğünü gör.)",
 ["Aracın yapmadığı bir şeyi vaat etme.","Hesap sonucunu tavsiye gibi sunma."]),

C(20,"Topluluk içerikleri (anket, soru, journal inceleme)",
 "Topluluğa soru sorma, anket yapma ve onların paylaştığı örnekleri inceleme.",
 "Sosyal medya ve topluluk yöneticisi.","Haftada 1-2.",
 "Discord, story, X anketi, Telegram anketi.",
 ["Haftanın sorusunu seç: 'Bu hafta en büyük hatan neydi?'","Aynı soruyu Discord'da (general), X'te anket olarak, Instagram story'de anket olarak sor.","İlk saatlerde cevap verenlere teşekkür et, soru sor.","Cevaplardan sık geçenleri bir sonraki içerik fikri olarak not al.","Journal inceleme (Discord): kullanıcı kendi örnek işlemini paylaşırsa, kişisel bilgiyi sildirerek hep birlikte konuş."],
 "Discord: 'Haftanın sorusu: Kayıptan sonra ne kadar ara veriyorsun? A) hiç B) 15 dk C) 1 saat D) o gün bırakıyorum'",
 ["Sinyal soruları sorma ya da cevaplama.","Kimsenin hatasıyla alay etme."]),

C(21,"Yardım yorumları (Reddit, X, Discord, yorumlar)",
 "Başkalarının sorularına gerçekten yardımcı olan cevaplar yazma. Reklam değildir; bağlantı yok ya da çok az. Güven böyle kazanılır.",
 "Sosyal medya ve topluluk yöneticisi.","Haftada 3 Reddit yorumu; günlük X ve Discord yanıtları.",
 "Hesaplara giriş (yöneticiden).",
 ["Reddit/X'te 'trading journal', 'position size' gibi soruları ara.","Soruyu dikkatle oku: kişi ne bilmek istiyor?","Cevabı yaz: %90 bilgi, en çok %10 bağlantı. Bağlantı yoksa daha iyi.","Gönderiyi yayınlamadan önce subreddit kurallarını oku.","Cevap çok uzunsa adım adım madde madde yaz."],
 "Soru: 'How do I decide how big my position should be?'\nCevap: 'A common way is to decide how much money you are willing to lose first. Say 1% of your account. If your account is 10,000, that is 100. Then you divide that by the distance to your stop, in money per lot. This is just an example, not advice.'",
 ["Yeni hesapla bağlantı koyma (spam sayılır, ban olur).","'Bizim ürünü kullan' diye cevap verme.","Tartışmaya kapılma: kaba kişiye cevap verme."]),

C(22,"Vaka çalışması (gerçek kullanıcı hikâyesi)",
 "Bir kullanıcının, programı kullanarak neyi fark ettiğini anlattığı içerik. Yalnız gerçek ve izinli olur. İlk gerçek kullanıcılar gelene kadar yapılmaz.",
 "Yazar / video yapımcısı; yönetici izni alır.","İlk kullanıcılardan sonra; ayda 1.",
 "Kullanıcının yazılı izni.",
 ["Kullanıcıya izin sor: ad kullanabilir miyiz? Hangi bilgi paylaşılır?","İzni yazılı al (e-posta yeterli, saklanır).","Röportaj yap (kısa, 5 soru).","Metni kullanıcıya göster, onayını al.","Kullanıcıya ödül ya da karşılık verildiyse metne yaz.","Danışman ve yönetici onayı, yayın."],
 "Başlık: 'İntikam işlemlerini nasıl azalttı?' (kullanıcı izniyle)\nSoru örneği: 'Programı kullanmadan önce neyi fark etmiyordun? Hangi alışkanlığını gördün? Ne değiştirdin?'",
 ["Uydurma kullanıcı hikâyesi yazma (yasak).","İzinsiz isim ya da ekran görüntüsü kullanma.","Para kazandığını gösterme."]),

C(23,"Perde arkası ve yapım süreci",
 "Ürünün nasıl geliştiğini ve ekibin ne yaptığını anlatan samimi kısa içerik. Markaya insan yüzü katar.",
 "Sosyal medya yöneticisi; geliştiriciden bilgi alır.","Haftada 1.",
 "Geliştiricinin haftalık notu.",
 ["Geliştiriciye sor: bu hafta ne ekledik, ne düzelttik?","Üç madde yaz.","Story, X ya da kısa video olarak paylaş.","Doğru olmayan bir iddia kurma (örneğin 'binlerce kullanıcı')."],
 "X metni: 'This week we shipped: a prop firm limit indicator and a fix for MT4 file import. Next up: a new calculator.'\n(Türkçesi: Bu hafta: prop firma limit göstergesi ve MT4 dosya içe aktarma düzeltmesi. Sırada yeni bir hesap makinesi.)",
 ["Abartılı sayı yazma.","Yayında olmayan özelliği 'çıktı' diye yazma."]),
]
