# Tablodaki işaretlerin platform bölümlerinde karşılığı olan ek bloklar.
# (tür numaraları, başlık, açıklama, [örnekler: her satır "Tür: nasıl uyarlanır"])
EXTRA={
"Instagram":[
 ("1 · 11 · 12 · 21 · 22","Diğer içeriklerin Instagram'a uyarlanması","Instagram'a özel üretilmeyen ama bu kanala uyarlanan içerikler. Hepsi mevcut içerikten türetilir, ek üretim yükü azdır.",
  ["Uzun video (tür 1): en iyi 30-60 saniyelik kesit Reels olur; 'tamamı YouTube'da' notu ve bağlantı story'de.",
   "Kapak ve görseller (tür 11): hesap kapağı, öne çıkan simgeleri ve story şablonları marka kitine göre hazırlanır.",
   "Şablonlar (tür 12): PDF paylaşılamaz; karusel kartı ya da story ile tanıtılır, bağlantı biyografide ('kontrol listesi PDF: biyografideki bağlantı').",
   "Yardım yorumları (tür 21): gönderi ve Reels altındaki sorulara ayrıntılı cevap; sık gelen soru story ya da Reels konusu olur.",
   "Vaka çalışmaları (tür 22, sonra): izinli gerçek kullanıcı hikâyesi karusel olarak."]),
],
"X":[
 ("7 · 9 · 12 · 17 · 18 · 22","Diğer içeriklerin X'e uyarlanması","Karusel, infografik, şablon, bülten ve sözlük gibi içerikler X'te kısa ve görsel olarak paylaşılır.",
  ["Karusel (tür 7): ilk kart tek görselle, kalan kartlar thread içinde ya da tek tweette 4 görsel.",
   "İnfografik (tür 9): tek görsel ve bir cümlelik açıklama.",
   "Şablonlar (tür 12): PDF yüklenmez; indirme bağlantısı tweet'e konur.",
   "Haftalık bülten (tür 17): pazar günü 'bu hafta' özeti ve abone bağlantısı.",
   "Sözlük ve SSS (tür 18): haftada bir 'Terim: ...' tweet'i ve sözlük bağlantısı.",
   "Vaka çalışmaları (tür 22, sonra): izinli alıntı ve bağlantı."]),
],
"YouTube":[
 ("12 · 19 · 21 · 22 · 23","Araç, şablon ve topluluk içerikleri","Araç ve şablonlar YouTube'a yüklenemez; YouTube'da bunları anlatan videolar ve bağlantılar olur.",
  ["Hesap makineleri (tür 19): 3-5 dakikalık ekran kaydı anlatım videosu: aracı aç, örnek değer gir, sonucu açıkla. Açıklamada ve sabit yorumda araç bağlantısı. Aynı videodan 30-60 saniyelik Shorts. Örnek: 'Pozisyon büyüklüğü hesap makinesi nasıl kullanılır?'",
   "Şablonlar (tür 12): PDF yüklenemez; açıklamaya ve sabitlenmiş yoruma indirme bağlantısı konur.",
   "Yardım yorumları (tür 21): yorumlara düzenli cevap; sık gelen sorular sonraki videonun konusu olur.",
   "Vaka çalışmaları (tür 22, sonra): izinli kullanıcı hikâyesi videosu.",
   "Yapım süreci (tür 23): ayda 1 'Ürüne neler ekledik' kısa videosu."]),
],
"TikTok":[
 ("1","Uzun videodan kesit","YouTube'daki uzun eğitim videosundan en güçlü 30-60 saniyelik kesit dikey formatta kırpılır, altyazılanır ve TikTok'a yüklenir; 'tamamı YouTube'da' notuyla.",
  ["Trading journal nasıl tutulur? (en önemli adım, 45 saniye)"]),
],
"Telegram":[
 ("1 · 5 · 6 · 7 · 9 · 16 · 22 · 23","Diğer içeriklerin Telegram'a uyarlanması","Kanal bu içeriklerin hepsini kısa metin ve görselle duyurur; kullanıcı kaçırmasın diye.",
  ["Uzun eğitim videosu (tür 1): 3 cümlelik özet ve YouTube bağlantısı.",
   "Prop firma kural rehberi (tür 5): kısa video doğrudan yüklenir, rehberin bağlantısı eklenir.",
   "Canlı yayın (tür 6): yayından bir gün önce hatırlatma, yayın başlayınca bağlantı.",
   "Karusel ve infografik (tür 7 ve 9): kartlar albüm olarak paylaşılır.",
   "Kısa metin ve thread (tür 16): thread tek mesajda toplanır.",
   "Vaka çalışmaları (tür 22, sonra): izinli kullanıcı hikâyesi.",
   "Yapım süreci (tür 23): haftalık 'bu hafta ürüne eklediklerimiz' mesajı."]),
],
"Facebook":[
 ("1 · 9 · 10 · 16 · 19 · 20","Önemli içeriklerin ayrıca paylaşılması","Instagram'dan otomatik yansıyanlara ek olarak, önemli olanlar Facebook'ta ayrıca öne çıkarılır.",
  ["Uzun video (tür 1): kesit ve YouTube bağlantısı.",
   "İnfografik ve ürün güncellemesi (tür 9 ve 10): tek görsel ve kısa açıklama.",
   "Kısa metin (tür 16): haftada 1 seçilmiş ipucu.",
   "Hesap makineleri (tür 19): yeni araç çıkınca duyuru.",
   "Topluluk içerikleri (tür 20): aylık anket, canlı yayın hatırlatması."]),
],
"LinkedIn":[
 ("1 · 6 · 8 · 9 · 12 · 14 · 16 · 17 · 19","Diğer içeriklerin LinkedIn'e uyarlanması","LinkedIn'de içerikler daha az duygusal, daha çok veri ve disiplin odaklı yazılır.",
  ["Uzun video (tür 1): kesit ve YouTube bağlantısı.",
   "Canlı yayın (tür 6): etkinlik duyurusu ve kayıt bağlantısı.",
   "Kural kartı ve infografik (tür 8 ve 9): tek görsel, altına 3-4 cümlelik yorum.",
   "Şablonlar (tür 12): PDF 'belge' olarak yüklenir, LinkedIn kaydırmalı gösterir.",
   "Karşılaştırma yazıları (tür 14): bağlantı ve tek paragraflık özet.",
   "Kısa metin (tür 16): thread LinkedIn'de tek uzun gönderi olur.",
   "Bülten (tür 17): ayda bir 'bu ay' özeti.",
   "Hesap makineleri (tür 19): yeni araç duyurusu."]),
],
"Reddit":[
 ("9","Görsel ve şema paylaşımı","Yardım yorumlarında formül şeması ya da basit bir görsel kullanılabilir (subreddit izin veriyorsa); anlatımı destekler, reklam gibi durmamalı.",
  ["R-multiple hesabı için tek görsel şema"]),
],
"Discord":[
 ("1 · 2 · 5 · 9 · 15 · 18 · 22 · 23","Diğer içeriklerin Discord'a uyarlanması","Topluluk bu içerikleri hem duyuru hem tartışma konusu olarak görür.",
  ["Uzun video (tür 1): announcements'ta bağlantı, general'da tartışma sorusu.",
   "Ürün turu ve prop firma rehberi (tür 2 ve 5): kısa video doğrudan yüklenir.",
   "İnfografik (tür 9): general'da paylaşılır ve tartışılır.",
   "Prop firma sayfaları (tür 15): bir firmanın kuralı değişince bildirim.",
   "Sözlük ve yardım (tür 18): support kanalında sık sorulara bağlantı.",
   "Vaka çalışmaları (tür 22, sonra): izinli kullanıcı hikâyesi.",
   "Yapım süreci (tür 23): haftalık 'bu hafta' notu."]),
],
}
