# Her platform: (ad, adres, durum, rol, [içerikler], [(etiket, metin)])
# içerik: (tür numaraları, başlık, açıklama, [örnekler])
P=[
("Web sitesi","simpletradejournal.io","Açık",
 "Tüm trafiğin toplandığı merkez. Sosyal kanallar buraya bağlantı verir; Google'dan gelen arama trafiği de buraya düşer. Burada yayınlanan her şey kalıcıdır ve aramalarda aylarca, yıllarca trafik getirir.",
 [("13","Blog yazıları","Haftada 1 yazı. Dört kümede ilerler: journal ve metrikler, trader psikolojisi, risk yönetimi, prop firma. Her yazı aynı iskeleti izler: net başlık, 3 cümlelik giriş (okuyucu ne öğrenecek), adım adım anlatım, örnek hesap (demo veriyle ve 'örnek' diye işaretli), 'journal'da bunu nasıl görürsün' bölümü, ilgili araç ve yazılara bağlantı, sık sorulan sorular. Her yazının sonunda ücretsiz hesap açma çağrısı.",
   ["Başabaş win rate nasıl hesaplanır?","Drawdown nedir, kayıptan sonra ne kadar kâr gerekir?","Haftalık gözden geçirme: 20 dakikada işlemlerini nasıl okursun?"]),
  ("14","Karşılaştırma yazıları","'X alternatifi' kalıbında, satın almaya yakın aramalar için. Adil bir yan yana tablo: fiyat, MetaTrader senkronu, desteklenen platformlar, disiplin analizi, prop firma takibi. Rakibin güçlü yanları da yazılır; bu güveni artırır. Fiyat ve özellik bilgileri tarihle yazılır ve düzenli kontrol edilir.",
   ["Yayında: Tradezella, TraderSync, Edgewonk, Tradervue, TradesViz ve FX Replay alternatifi","Yeni rakip çıktıkça aynı şablonla yeni sayfa"]),
  ("15","Prop firma ve broker sayfaları","Her firma ve broker için ayrı sayfa. İçerik: kural özeti (günlük kayıp, toplam kayıp, drawdown türü), 'bunu journal'da nasıl takip edersin' adımları, sık sorulan sorular, sayfanın en altında 'kurallar değişebilir, resmi sayfayı kontrol et' notu ve son kontrol tarihi. Kurallar aylık kontrol edilir.",
   ["FTMO kuralları takip aracı","IC Markets MT5 raporu içe aktarma","Sıradaki: FundedNext, FXIFY"]),
  ("19","Ücretsiz hesap makineleri","Her araç kendi sayfasında: basit bir form, anında sonuç, formülün açıklaması, bir örnek senaryo, sık sorulan sorular ve ilgili yazıya bağlantı. Araçlar arama trafiği çeker ve paylaşılabilir. Yeni araçlar aynı şablonla eklenir.",
   ["Pozisyon büyüklüğü, risk/ödül, prop firma kaybı (var)","Sıradaki: beklenti hesaplayıcı, başabaş win rate, drawdown toparlanma hesaplayıcısı"]),
  ("18","Sözlük ve yardım sayfaları","Trading terimleri sözlüğü (her terim kısa ve net, ilgili yazıya bağlantılı) ve yardım sayfası: MetaTrader kurulumu, içe aktarma, hesap sorunları. Yardım sayfasında sık sorulan sorular arama sonuçlarında zengin sonuç olarak çıkar.",
   ["Trading terimleri sözlüğü","MetaTrader kurulumu adım adım"]),
  ("12 · 17","İndirilebilir şablonlar ve haftalık bülten","İşlem öncesi kontrol listesi ve haftalık gözden geçirme sayfası PDF olarak sunulur. İndirmek isteyenden e-posta istenir, karşılığında şablon ve haftalık bülten gelir. Bülten arşivi sitede durur.",
   ["İşlem öncesi kontrol listesi (PDF)","Haftalık gözden geçirme sayfası (PDF)"]),
  ("1 · 2 · 5","Gömülü videolar","İlgili yazı ve yardım sayfasına YouTube videosu gömülür: kurulum videosu yardım sayfasına, eğitim videosu blog yazısına, prop firma rehberi firma sayfasına. Hem sayfada kalma süresini artırır hem YouTube'a trafik gönderir.",
   ["MT5 kurulum videosu yardım sayfasında"]),
  ("9 · 10 · 11 · 23","Görseller, değişiklik günlüğü ve yapım süreci","Her yazıya özgün kapak ve gerekirse infografik (formül şeması). Değişiklik günlüğü her yayında güncellenir: ne eklendi, ekran görüntüsüyle kısa açıklama. Yapım süreci (tür 23) de burada: ayda 1 kısa yazı, bu ay ürüne neler eklediğimiz.",
   ["R-multiple şeması","Değişiklik günlüğü: yeni özellik girişi"]),
  ("22","Vaka çalışmaları (ilk kullanıcılardan sonra)","Gerçek bir kullanıcının, yazılı izinle, journal ile neyi fark ettiğini anlattığı sayfa. Uydurma yok; kullanıcı yoksa yayınlanmaz.",
   ["'İntikam işlemlerini nasıl azalttım?' kullanıcı hikâyesi"])],
 [("Hedef","Haftada 1 yeni yazı; ayda 1 yeni araç ya da firma sayfası kümesi; değişiklik günlüğü her yayında."),
  ("Reklam","Yok. Büyüme arama motorundan."),
  ("Dikkat","Her yeni sayfa 9 dilde yayınlanır, Search Console ve IndexNow'a bildirilir. Kâr vaadi yok; örnek hesaplar 'örnek hesaptır, tavsiye değildir' notuyla."),
  ("Ölçüm","Search Console tıklamaları ve sorgular, kayıt sayısı, hangi yazının kayıt getirdiği.")]),

("Instagram","@simpletradejournal","Açık",
 "Görsel vitrin ve günlük temas. Kaydırmalı kartlarla tanınırlık, Reels ile yeni kitleye ulaşma, story ile günlük bağ. Threads otomatik gelir. Reklam hesabı Facebook ile birlikte yönetilir.",
 [("7","Karusel gönderileri (haftada 2)","5-7 kartlık kaydırmalı gönderi. Kart 1: dikkat çeken başlık. Kart 2-5: adım adım anlatım. Kart 6: özet. Son kart: 'Kaydet' ve 'hesap makinesi biyografide' çağrısı. Aynı kartlar LinkedIn'de PDF karusel olur. Koyu zemin, altın vurgu, Newsreader başlık (marka kiti).",
   ["Pozisyon büyüklüğü 5 adımda","İntikam işleminin 4 işareti","Haftalık gözden geçirme nasıl yapılır?"]),
  ("8 · 9","Kural kartları ve infografikler","Tek görsel, tek fikir: bir disiplin kuralı ya da bir formül şeması. Hızlı üretilir, çok paylaşılır. Altına 2-3 cümlelik açıklama yazılır.",
   ["Kayıptan sonra ilk işlemi yazmadan açma","Beklenti = (kazanma oranı × ort. kazanç) − (kaybetme oranı × ort. kayıp)"]),
  ("10","Ürün güncelleme görselleri","Yeni özelliğin ekran görüntüsü ve bir cümlelik fayda. Şablon her seferinde aynı olur, böylece 'yeni özellik' kartı tanınır.",
   ["Yeni: prop firma limit göstergesi"]),
  ("3 · 4 · 2 · 5","Reels (haftada 3)","30-60 saniye, dikey (9:16), altyazılı, ilk 3 saniyede konu. Dört biçim: kısa ipucu (tek fikir), hata analizi (demo işlemde hatayı bul), ürün turu kesiti (tek özellik, 20 saniye), prop firma kuralı kesiti. YouTube Shorts ve TikTok ile aynı çekim.",
   ["R-multiple 30 saniyede","Bu işlemde hatayı bul","MT5'ten otomatik senkron: tek tıkla"]),
  ("20 · 13 · 19 · 23","Story (günlük)","Günde 3-5 story. Anket ve soru kutusu ('Günde kaç işlem açıyorsun?'), 'bugünün kuralı', yeni yazı ve araç bağlantısı (bağlantı çıkartmasıyla), perde arkası (ne üzerinde çalışıyoruz). Story'ler 24 saatte kaybolur; önemlileri öne çıkanlara taşınır.",
   ["Anket: kayıptan sonra ara veriyor musun?","Yeni araç: risk/ödül hesap makinesi"]),
  ("6","Canlı yayın (ayda 1)","Topluluğun sorularını canlı cevaplama. Önceden story'de soru toplanır. Kayıt, YouTube'da uzun video ve kısa videolara bölünür.",
   ["Ayın soru-cevap yayını"]),
  ("Öne çıkanlar","Kalıcı story koleksiyonları","Beş başlık: Başla (kurulum), Araçlar, SSS, Güncellemeler, Eğitim.",
   [])],
 [("Hedef","Haftada 2 karusel, 3 Reels, günlük story, ayda 1 canlı yayın."),
  ("Reklam","Şimdilik yok (şirket ve Pixel sonrası)."),
  ("Dikkat","Gönderi içine bağlantı konmaz, bağlantı biyografide ve story'de. Facebook'a otomatik yansır. Gerçek hesap ekran görüntüsü paylaşılmaz."),
  ("Ölçüm","Kaydetme ve paylaşım sayısı, biyografi bağlantı tıklaması, story anket katılımı.")]),

("X","@SimpleTradeJrnl","Açık",
 "Trader topluluğunun tartışma yeri: hızlı ipuçları, ürün duyuruları, yardım yanıtları. Organik büyüme; reklam yok.",
 [("16","Günlük ipucu (günde 1-2)","Tek cümlelik risk ve disiplin kuralı ya da kısa bir gözlem. Bazılarının altına araç ya da yazı bağlantısı konur. Haftada 1 tanesi görsel kartla.",
   ["Pozisyon büyüklüğü giriş fiyatından önce belli olmalı.","Günlük kayıp limitin dolunca günün işlemi biter."]),
  ("16","Thread (haftada 1)","5-8 tweetlik anlatım: ilk tweet kanca, sonra adımlar, son tweet özet ve bağlantı. Blog yazısından türetilir.",
   ["Bir intikam işleminin anatomisi","R-multiple: işlemleri aynı ölçüyle karşılaştır"]),
  ("3 · 4 · 2 · 5","Kısa video paylaşımı (haftada 2-3)","Reels, TikTok ve Shorts için çekilen aynı video X'e de doğrudan yüklenir (bağlantı değil, video dosyası; X içinde oynar). İzleyen çoğu kişi sesi kapalı izler: altyazı şart. Tweet metni kısa: tek cümle kanca ve gerekirse araç ya da yazı bağlantısı. Başka platformun filigranıyla yüklenmez; orijinal dosya kullanılır.",
   ["R-multiple 30 saniyede (video)","Bu işlemde hatayı bul (video)","MT5 senkron: 20 saniyelik ürün turu"]),
  ("8 · 10","Kural kartı ve ürün duyurusu","Kural kartı haftada 1. Ürün güncellemesi: kısa ekran kaydı ya da GIF ve tek cümle.",
   ["Yeni özellik: haftalık özet e-postası"]),
  ("19","Araç paylaşımı","Hesap makinesinin ekran görüntüsü ve 'ücretsiz' notu, bağlantıyla. Yeni araç çıkınca ve ara sıra tekrar.",
   ["Risk/ödül hesap makinesi"]),
  ("20","Anketler","Haftada 1 anket: topluluğun alışkanlıklarını sorar, sonuçlar sonraki içeriğe fikir olur.",
   ["Günde kaç işlem açıyorsun?"]),
  ("21","Yardım yanıtları","Trader'ların sorularına gerçek yardım: bağlantı yok ya da yalnız profilden. Arama: 'trading journal', 'position size'.",
   []),
  ("23","Yapım süreci paylaşımı","Ne yaptık, ne öğrendik, ne geliyor. Gerçek sayılar yalnız doğruysa; abartı yok.",
   ["Bu hafta ürüne eklediklerimiz"]),
  ("13 · 14 · 15 · 1 · 6","Bağlantı ve duyuru paylaşımları","Yeni blog yazısı, firma sayfası, uzun video ve canlı yayın duyurusu. Her biri için bir tweet; uzun videodan 30-60 saniyelik kesit doğrudan yüklenir. Tekrar paylaşım haftalar sonra.",
   [])],
 [("Hedef","Günde 1-2 paylaşım, haftada 2-3 video, haftada 1 thread, haftada 1 anket."),
  ("Reklam","Yok."),
  ("Dikkat","Hesap adı 15 karakter sınırı yüzünden @SimpleTradeJrnl. Sinyal, fiyat tahmini ve 'şu işlemi aç' yok."),
  ("Ölçüm","Profil ziyareti, bağlantı tıklaması, thread okunma ve kaydetme.")]),

("YouTube","@simpletradejournal (hedef)","Henüz açılmadı: admin@ hesabı 30 günlük olunca (11 Ekim sonrası)",
 "Eğitim ve kurulum videolarının evi. Google'da da çıkar; bir kez yüklenen video uzun süre izlenir. Marka hesabı, ad Simple Trading Journal; logo, kapak ve açıklamada site bağlantısı.",
 [("1","Uzun eğitim videoları (haftada 1)","8-15 dakikalık, ekran kaydı ve anlatım. Yapı: ilk 15 saniyede ne öğrenilecek, adım adım anlatım, örnek (demo veriyle), özet ve çağrı. Her video için anahtar kelimeli başlık, ayrıntılı açıklama (site bağlantısı, bölüm zaman damgaları), altyazı ve özel thumbnail.",
   ["Trading journal nasıl tutulur? 10 dakikada adım adım","R-multiple nedir, nasıl hesaplanır?","Beklenti ve kâr faktörü: stratejin çalışıyor mu?"]),
  ("2","Kurulum ve ürün turu","Ekran kaydıyla MetaTrader (MT4 ve MT5) otomatik senkron kurulumu ve dosya içe aktarma; özelliklerin gezdirilmesi. Yardım sayfasına ve ilgili yazılara gömülür.",
   ["MT5'ten otomatik senkron: kurulum 5 adımda","MT4 raporunu içe aktarma"]),
  ("5","Prop firma kural rehberleri","Günlük kayıp limiti, toplam kayıp ve drawdown türleri; journal'da takip. Her firma için ayrı video, firma sayfasına gömülür. Kural değişince güncellenir ya da not düşülür.",
   ["Günlük kayıp limitini nasıl takip edersin?","FTMO kuralları ve takip aracı"]),
  ("6","Canlı yayın ve soru-cevap (ayda 1)","Topluluğun soruları canlı cevaplanır, kayıt kalıcı video olur ve kısa videolara bölünür.",
   ["Ayın soru-cevap yayını"]),
  ("3 · 4 · 2 · 5","Shorts: kısa ipucu ve hata analizi videoları (haftada 2-3)","Instagram Reels ve TikTok için çekilen kısa ipucu ile hata analizi videoları aynı çekimle YouTube Shorts olarak da yüklenir; uzun video olmasa bile kanal Shorts ile büyür. Ek olarak her uzun videodan 1-3 kısa kesit çıkarılır. Her Shorts için başlık ve açıklama YouTube için ayrıca yazılır, sonunda uzun videoya ya da ilgili listeye yönlendirme olur. Başka platformun filigranı olmayan orijinal dosya yüklenir.",
   ["R-multiple 30 saniyede","Bu işlemde hatayı bul"]),
  ("11","Thumbnail ve kanal görselleri","Her video için marka kitine uygun kapak: kısa başlık, altın vurgu, ekran görüntüsü. Kanal afişi hazır (cover-yt.png).",
   []),
  ("Düzen","Oynatma listeleri ve kanal içi yönlendirme","Beş liste: Başlangıç, Risk, Psikoloji, MetaTrader Kurulumu, Prop Firma Kuralları. Her videonun sonunda end screen, açıklamada ilgili yazı ve araç bağlantısı, sabitlenmiş yorumda soru.",
   [])],
 [("Hedef","Haftada 1 uzun video, 2-3 Shorts."),
  ("Reklam","Yok."),
  ("Dikkat","Para kazandığını gösteren ekran kaydı yok; hesap bakiyesi yalnız demo. 'Garanti', 'kesin kazanç' dili yok."),
  ("Ölçüm","İzlenme süresi, thumbnail tıklanma oranı, açıklamadan site tıklaması.")]),

("TikTok","kullanıcı adı otomatik verildi; 30 Ekim'den sonra simpletradejournal","Açık (adı bekliyor)",
 "Hızlı keşif kanalı; genç trader'lara ulaşmak için. Reels ve Shorts ile aynı çekimler kullanılır, ek üretim yükü az.",
 [("3","Kısa ipucu videoları (haftada 3)","15-45 saniye, dikey, altyazılı. Tek fikir: bir kural ya da bir kavram. İlk 3 saniyede konu ve merak.",
   ["R-multiple 30 saniyede","Pozisyon büyüklüğünün en sık hatası"]),
  ("4","Hata analizi","Demo işlemde bir hata gösterilir ve nedeni açıklanır. İzleyiciye soru sorarak biter ('Sen ne yapardın?').",
   ["Aşırı işlemin 3 işareti","Kayıptan sonra ilk işlem"]),
  ("2 · 19","Ekran kaydı hızlı ipuçları","Tek özellik, tek ekran kaydı: dosya içe aktarma, hesap makinesi, takvim. 15-30 saniye.",
   ["2 saniyede MT5 raporu içe aktar"]),
  ("5 · 23","Kesitler ve süreç videoları","Prop firma kuralından 30 saniyelik kesit; 'journal'ımı nasıl dolduruyorum' (demo hesapla); yapım süreci.",
   []),
  ("21","Yoruma video cevap","Gelen soruya kısa video ile cevap verme özelliği. Konu çıkarmanın ve etkileşimin kolay yolu.",
   [])],
 [("Hedef","Haftada 3 video."),
  ("Reklam","Yok."),
  ("Dikkat","İş hesabı olarak ayarlı (istatistik için). Kâr gösteren ekran görüntüsü ve sinyal yok. Kullanıcı adı 30 gün sonra düzeltilecek."),
  ("Ölçüm","Tamamlanma oranı, paylaşım, profil ziyareti.")]),

("Telegram","t.me/simpletradejournal","Açık",
 "Duyuru kanalı: doğrudan ve düzenli temas. Abone, bildirimi açtığı için her paylaşım görülür. Kanal herkese açık, sabitlenmiş mesajda kısa tanıtım ve site bağlantısı.",
 [("8","Günlük kural","Tek satırlık disiplin hatırlatması, istenirse kart görseliyle. Her sabah aynı saatte; alışkanlık oluşturur.",
   ["Bugünün kuralı: günlük kayıp limitin dolunca dur."]),
  ("13 · 14 · 15","Yeni yazı özeti","Yazı yayınlanınca 3-4 cümlelik özet ve bağlantı. Metin İngilizce; Türkçe (istenirse Farsça) çevirisi aynı mesajın altına eklenir.",
   ["Yeni yazı: Drawdown'dan çıkış matematiği"]),
  ("3 · 4 · 2","Kısa videolar (haftada 2)","Reels, TikTok ve Shorts için çekilen kısa videolar Telegram kanalına doğrudan yüklenir; altyazı ve tek cümlelik açıklama eklenir. Uzun videolar için YouTube bağlantısı verilir.",
   ["Bu işlemde hatayı bul (video)","R-multiple 30 saniyede"]),
  ("19 · 10","Araç ve özellik duyuruları","Yeni hesap makinesi ya da özellik: ne işe yarar, bağlantı, kısa ekran görüntüsü.",
   ["Yeni araç: beklenti hesaplayıcı"]),
  ("12","Şablon dağıtımı","Kontrol listesi ve gözden geçirme sayfası PDF olarak kanalda paylaşılır.",
   ["İşlem öncesi kontrol listesi (PDF)"]),
  ("20","Anketler","Telegram'ın anket özelliğiyle haftada 1 soru.",
   ["Günde kaç işlem açıyorsun?"]),
  ("17","Haftalık özet","Pazar günü: haftanın yazıları, araçları ve güncellemeleri tek mesajda.",
   [])],
 [("Hedef","Günde 1 paylaşım, haftada 1 özet."),
  ("Reklam","Yok."),
  ("Dikkat","Çok sık paylaşım aboneyi rahatsız eder, çok az paylaşım kanalı ölü gösterir. Sinyal paylaşılmaz."),
  ("Ölçüm","Abone sayısı, mesaj görüntülenmesi, bağlantı tıklaması.")]),

("Facebook","facebook.com/simpletradejournalapp","Açık",
 "Meta reklam hesabı ve Pixel için gerekli sayfa. Ek içerik üretilmez, zaman harcanmaz: Instagram gönderileri otomatik yansır. Sayfa 'var olsun' modunda çalışır; kapatılmaz.",
 [("3 · 4 · 2 · 5 · 7 · 8","Instagram'dan otomatik yansıyanlar","Karusel, kural kartı ve tüm Reels'ler (kısa ipucu, hata analizi, ürün turu, prop firma kuralı) Facebook'a da düşer; ayrıca bir şey yapılmaz. İstenirse video orijinal dosyadan doğrudan da yüklenir.",
   []),
  ("13","Yeni yazı paylaşımı","Önemli bir blog yazısı ayda 1-2 kez bağlantıyla paylaşılır.",
   []),
  ("6","Etkinlik","Ayda bir canlı soru-cevap yayını için Facebook etkinliği açılır.",
   [])],
 [("Hedef","Yok; otomatik yansıma yeter. Ayda bir sayfa bilgilerinin güncelliği kontrol edilir."),
  ("Reklam","Şimdilik yok; ileride Instagram üzerinden verilecek, Facebook'a yansıyacak."),
  ("Dikkat","İkinci yönetici ve Meta Business'ta 'Simple Trading Journal' portföyü kurulacak."),
  ("Ölçüm","Yok (yalnız sayfa varlığı).")]),

("LinkedIn","linkedin.com/company/simpletradejournal","Açık",
 "Profesyonel trader'lar, prop firma ve broker ortakları, kurumsal imaj. Dil duygusal değil, veri ve disiplin odaklı.",
 [("7","PDF karusel (haftada 1)","Instagram karuseli PDF olarak yüklenir (LinkedIn belgeyi kaydırmalı gösterir). Kurumsal ton: daha az emoji, daha çok veri.",
   ["Haftalık gözden geçirme şablonu","Prop firma günlük kayıp limiti: 5 kontrol"]),
  ("3 · 4 · 5 · 2","Kısa videolar (haftada 1-2)","Kısa ipucu, hata analizi ve prop firma kuralı videoları LinkedIn'e doğrudan yüklenir; altyazılı. Ton kurumsal, açıklama veri ve disiplin odaklı. Eğlence ya da trend formatları burada paylaşılmaz.",
   ["Prop firma günlük kayıp limiti: 40 saniyede","R-multiple 30 saniyede"]),
  ("13 · 15","Makaleler ve kısa yazılar","Blog yazısının kısa versiyonu ve prop firma trader'ları için disiplin ve risk yazıları. Sonda sitedeki yazıya bağlantı.",
   ["Kayıp serilerinde risk nasıl azaltılır?"]),
  ("10","Ürün güncellemeleri","Önemli özellikler: ne eklendi, kime ne fayda sağlar. Kısa ve ekran görüntülü.",
   []),
  ("22","Vaka çalışmaları (sonra)","Gerçek kullanıcıdan izinle. İlk kullanıcılardan sonra.",
   []),
  ("23","Kurucu ve yapım süreci","Neden bu ürünü yaptık, neyi öğrendik. Kişisel profilden paylaşılır; kişisel profiller şirket sayfasından daha çok görünür.",
   ["Neden bir trading journal yaptık?"]),
  ("5 · 20","Prop firma ve topluluk içerikleri","Prop firma kural rehberi (video) ve anketler: 'Hangi prop firma kuralı seni en çok zorluyor?'",
   [])],
 [("Hedef","Haftada 2 gönderi. Kalite miktardan önemli."),
  ("Reklam","Yok."),
  ("Dikkat","Ortaklık duyurusu ancak ilk bağlantıdan sonra. Hashtag: #TradingJournal #PropFirm #RiskManagement."),
  ("Ölçüm","Gönderi gösterimi, takipçi artışı, site tıklaması.")]),

("Reddit","u/simpletradejournal","Açık (paylaşım yok)",
 "Reklam değil, yardım. Topluluk güveniyle yavaş büyür; reklam yapanı hemen banlar. Hedef subredditler: r/Forex, r/Daytrading ve benzerleri. Her subredditin kuralları paylaşımdan önce okunur.",
 [("21","Yardım yorumları (haftada 3)","Bir trader 'journal nasıl tutulur', 'pozisyon büyüklüğü nasıl hesaplanır' diye sorduğunda gerçekten yardımcı olan, ayrıntılı bir cevap yazılır. Bağlantı yok ya da yalnız profil. Cevap tek başına değerli olmalı.",
   ["'How do I size my position on a 1% risk?' sorusuna adım adım cevap"]),
  ("13","Uzun eğitim gönderileri (ayda 1-2, ilk 2 aydan sonra)","Sitedeki bir yazının, bağlantısız ve kendi başına değerli uzun versiyonu. Subreddit kuralları izin veriyorsa.",
   ["R-multiple ile işlemleri karşılaştırmak: kısa rehber"]),
  ("20","Geri bildirim ve AMA (sonra)","'Bir trading journal'da hangi metrik eksik?' gibi gönderi ve izinli subredditlerde soru-cevap. Reklam gibi durmamalı.",
   []),
  ("19","Araç paylaşımı (kurallara uygunsa)","Bir hesap makinesini ücretsiz araç olarak paylaşmak ancak subreddit izin veriyorsa ve hesap yeterince eskiyse.",
   [])],
 [("İlk dönem","İlk 1-2 ay yalnız okuma ve yorum; link koymak yok."),
  ("Hedef","Haftada 3 yorum."),
  ("Dikkat","Yeni hesapla bağlantı koymak spam sayılır. Kâr paylaşımı ve sinyal yok. Gönderiler kolayca silinir ve hesap banlanabilir; acele edilmez."),
  ("Ölçüm","Yorumun puanı ve cevapları, profil ziyareti.")]),

("Discord","discord.gg/yUJ5NXyJHg","Açık",
 "Kullanıcı topluluğu, destek ve geri bildirim. Kanallar: welcome, announcements, general, support, feedback; LANGUAGES: turkish, persian. Sunucu canlı tutulmazsa boş görünür.",
 [("10 · 13 · 19","Duyurular (haftada 1)","Yeni özellik, yeni yazı, yeni araç. Kısa, bağlantılı, ekran görüntülü. announcements kanalı yalnız okunur.",
   ["Yeni: prop firma limit göstergesi"]),
  ("20","Haftalık tartışma sorusu","Her pazartesi general kanalında bir soru: topluluğu konuşturmak için.",
   ["Bu hafta en büyük hatan neydi?","Kayıptan sonra ne kadar ara veriyorsun?"]),
  ("20","Journal inceleme","Kullanıcı kendi (isterse kişisel veriyi gizleyerek) örnek işlemini paylaşır, topluluk ve ekip geri bildirim verir. Bir 'journal-review' kanalı sonra açılır.",
   []),
  ("6","Aylık ses odası","Ayda 1 soru-cevap; kaydı kısa videolara bölünür.",
   []),
  ("3 · 4 · 7 · 8","Görsel ve video paylaşımı","Kısa videolar, kartlar ve infografikler general kanalında paylaşılır; altına tartışma sorusu eklenir ('Bu işlemde sen ne yapardın?'). Hata analizi videoları journal inceleme tartışmasının da başlangıcı olur.",
   ["Bu işlemde hatayı bul (video)"]),
  ("12 · 21","Şablonlar ve yardım","Kontrol listesi ve gözden geçirme sayfası paylaşılır; support kanalında sorular cevaplanır. Sık gelen sorular yardım sayfasına eklenir.",
   [])],
 [("Hedef","Haftada 1 duyuru, 1 tartışma sorusu; support kanalına 24 saat içinde cevap."),
  ("Reklam","Yok."),
  ("Dikkat","Kurallar welcome kanalında (EN, TR, FA). Şifre ve API anahtarı paylaşımı yasak; 'ilk mesajı biz atmayız' notu."),
  ("Ölçüm","Üye sayısı, haftalık aktif üye, geri bildirim sayısı.")]),
]

from plat_extra import EXTRA
for _i,_row in enumerate(P):
    _row[4].extend(EXTRA.get(_row[0],[]))
