import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en' | 'fa' | 'ar' | 'ru' | 'es' | 'pt' | 'de' | 'fr';

interface Translations {
  [key: string]: { tr: string; en: string; fa: string; ar: string; ru: string; es: string; pt: string; de: string; fr: string; };
}

export const translations: Translations = {
  appTitle: { tr: 'Trade Journal', en: 'Trade Journal', fa: 'دفترچه معاملات', ar: 'سجل التداول', ru: 'Торговый журнал', es: 'Diario de Trading', pt: 'Diário de Trading', de: 'Trading Journal', fr: 'Journal de Trading' },
  dashboardTitle: { tr: 'Journal', en: 'Journal', fa: 'ژورنال', ar: 'السجل', ru: 'Журнал', es: 'Diario', pt: 'Diário', de: 'Journal', fr: 'Journal' },
  newJournal: { tr: 'Yeni Journal', en: 'New Journal', fa: 'ژورنال جدید', ar: 'سجل جديد', ru: 'Новый журнал', es: 'Nuevo Diario', pt: 'Novo Diário', de: 'Neues Journal', fr: 'Nouveau Journal' },
  newJournalSubtitle: { tr: 'Yeni bir işlem günlüğü başlat', en: 'Start a new trading journal', fa: 'یک دفترچه معاملاتی جدید شروع کنید', ar: 'ابدأ سجل تداول جديد', ru: 'Начать новый торговый журнал', es: 'Iniciar un nuevo diario de trading', pt: 'Iniciar um novo diário de trading', de: 'Neues Trading-Journal starten', fr: 'Démarrer un nouveau journal de trading' },
  newJournalDesc: { tr: 'Journal bilgilerini girin', en: 'Enter journal details', fa: 'جزئیات ژورنال را وارد کنید', ar: 'أدخل تفاصيل السجل', ru: 'Введите данные журнала', es: 'Ingrese los detalles del diario', pt: 'Insira os detalhes do diário', de: 'Journal-Details eingeben', fr: 'Entrez les détails du journal' },
  journalName: { tr: 'Journal Adı', en: 'Journal Name', fa: 'نام ژورنال', ar: 'اسم السجل', ru: 'Название журнала', es: 'Nombre del diario', pt: 'Nome do diário', de: 'Journal-Name', fr: 'Nom du journal' },
  journalNamePlaceholder: { tr: 'Örn: Prop Hesabım', en: 'e.g. My Prop Account', fa: 'مثال: حساب پراپ من', ar: 'مثال: حساب Prop الخاص بي', ru: 'Напр: Мой Prop счёт', es: 'Ej: Mi cuenta Prop', pt: 'Ex: Minha conta Prop', de: 'Z.B.: Mein Prop-Konto', fr: 'Ex: Mon compte Prop' },
  startDate: { tr: 'Başlangıç Tarihi', en: 'Start Date', fa: 'تاریخ شروع', ar: 'تاريخ البدء', ru: 'Дата начала', es: 'Fecha de inicio', pt: 'Data de início', de: 'Startdatum', fr: 'Date de début' },
  startingCapital: { tr: 'Başlangıç Sermayesi', en: 'Starting Capital', fa: 'سرمایه اولیه', ar: 'رأس المال الابتدائي', ru: 'Начальный капитал', es: 'Capital inicial', pt: 'Capital inicial', de: 'Startkapital', fr: 'Capital initial' },
  myJournals: { tr: 'Journallerim', en: 'My Journals', fa: 'ژورنال‌های من', ar: 'سجلاتي', ru: 'Мои журналы', es: 'Mis diarios', pt: 'Meus diários', de: 'Meine Journals', fr: 'Mes journaux' },
  noJournals: { tr: 'Henüz journal yok. Yeni bir tane oluştur!', en: 'No journals yet. Create a new one!', fa: 'هنوز ژورنالی وجود ندارد. یکی بسازید!', ar: 'لا توجد سجلات بعد. أنشئ واحداً جديداً!', ru: 'Журналов пока нет. Создайте новый!', es: '¡No hay diarios aún. Crea uno nuevo!', pt: 'Ainda não há diários. Crie um novo!', de: 'Noch keine Journals. Erstelle ein neues!', fr: "Pas encore de journaux. Créez-en un nouveau!" },
  backToDashboard: { tr: 'Dashboard', en: 'Dashboard', fa: 'داشبورد', ar: 'لوحة التحكم', ru: 'Панель', es: 'Panel', pt: 'Painel', de: 'Dashboard', fr: 'Tableau de bord' },
  newTradeTab: { tr: 'Yeni İşlem', en: 'New Trade', fa: 'معامله جدید', ar: 'صفقة جديدة', ru: 'Новая сделка', es: 'Nueva operación', pt: 'Nova operação', de: 'Neuer Trade', fr: 'Nouveau trade' },
  historyTab: { tr: 'İşlemler', en: 'Trades', fa: 'معاملات', ar: 'الصفقات', ru: 'Сделки', es: 'Operaciones', pt: 'Operações', de: 'Trades', fr: 'Trades' },
  calendarTab: { tr: 'Takvim', en: 'Calendar', fa: 'تقویم', ar: 'التقويم', ru: 'Календарь', es: 'Calendario', pt: 'Calendário', de: 'Kalender', fr: 'Calendrier' },
  statsTab: { tr: 'İstatistikler', en: 'Statistics', fa: 'آمار', ar: 'الإحصائيات', ru: 'Статистика', es: 'Estadísticas', pt: 'Estatísticas', de: 'Statistiken', fr: 'Statistiques' },
  goalsTab: { tr: 'Hedefler', en: 'Goals', fa: 'اهداف', ar: 'الأهداف', ru: 'Цели', es: 'Objetivos', pt: 'Metas', de: 'Ziele', fr: 'Objectifs' },
  formTitle: { tr: 'Yeni İşlem Kaydı', en: 'New Trade Record', fa: 'ثبت معامله جدید', ar: 'تسجيل صفقة جديدة', ru: 'Новая запись сделки', es: 'Nuevo registro de operación', pt: 'Novo registro de operação', de: 'Neuer Trade-Eintrag', fr: 'Nouveau enregistrement de trade' },
  formSubtitle: { tr: 'İşlem detaylarını, fotoğraflarını ve notlarını aşağıya girin.', en: 'Enter trade details, photos, and notes below.', fa: 'جزئیات معامله، عکس‌ها و یادداشت‌های خود را در زیر وارد کنید.', ar: 'أدخل تفاصيل الصفقة والصور والملاحظات أدناه.', ru: 'Введите детали сделки, фото и заметки ниже.', es: 'Ingrese los detalles de la operación, fotos y notas a continuación.', pt: 'Insira os detalhes da operação, fotos e notas abaixo.', de: 'Geben Sie Trade-Details, Fotos und Notizen unten ein.', fr: 'Entrez les détails du trade, les photos et les notes ci-dessous.' },
  dateTime: { tr: 'İşlem Tarihi ve Saati', en: 'Trade Date & Time', fa: 'تاریخ و زمان معامله', ar: 'تاريخ ووقت الصفقة', ru: 'Дата и время сделки', es: 'Fecha y hora de la operación', pt: 'Data e hora da operação', de: 'Datum und Uhrzeit des Trades', fr: 'Date et heure du trade' },
  symbol: { tr: 'Parite / Sembol', en: 'Pair / Symbol', fa: 'جفت ارز / نماد', ar: 'الزوج / الرمز', ru: 'Пара / Символ', es: 'Par / Símbolo', pt: 'Par / Símbolo', de: 'Paar / Symbol', fr: 'Paire / Symbole' },
  type: { tr: 'İşlem Türü', en: 'Trade Type', fa: 'نوع معامله', ar: 'نوع الصفقة', ru: 'Тип сделки', es: 'Tipo de operación', pt: 'Tipo de operação', de: 'Trade-Typ', fr: 'Type de trade' },
  buy: { tr: 'Buy', en: 'Buy', fa: 'Buy', ar: 'شراء', ru: 'Купить', es: 'Compra', pt: 'Compra', de: 'Kaufen', fr: 'Achat' },
  sell: { tr: 'Sell', en: 'Sell', fa: 'Sell', ar: 'بيع', ru: 'Продать', es: 'Venta', pt: 'Venda', de: 'Verkaufen', fr: 'Vente' },
  timeframe: { tr: 'Timeframe', en: 'Timeframe', fa: 'تایم‌فریم', ar: 'الإطار الزمني', ru: 'Таймфрейм', es: 'Marco temporal', pt: 'Tempo gráfico', de: 'Zeitrahmen', fr: 'Unité de temps' },
  setup: { tr: 'Setup / Strateji', en: 'Setup / Strategy', fa: 'ستاپ / استراتژی', ar: 'الإعداد / الاستراتيجية', ru: 'Сетап / Стратегия', es: 'Setup / Estrategia', pt: 'Setup / Estratégia', de: 'Setup / Strategie', fr: 'Setup / Stratégie' },
  rr: { tr: 'Risk/Reward (R/R)', en: 'Risk/Reward (R/R)', fa: 'ریسک/ریوارد (R/R)', ar: 'المخاطرة/المكافأة (R/R)', ru: 'Риск/Прибыль (R/R)', es: 'Riesgo/Recompensa (R/R)', pt: 'Risco/Retorno (R/R)', de: 'Risiko/Ertrag (R/R)', fr: 'Risque/Récompense (R/R)' },
  rrPlaceholder: { tr: 'Örn: 2.5', en: 'e.g., 2.5', fa: 'مثال: 2.5', ar: 'مثال: 2.5', ru: 'Напр.: 2.5', es: 'Ej: 2.5', pt: 'Ex: 2.5', de: 'Z.B.: 2.5', fr: 'Ex: 2.5' },
  risk: { tr: 'Risk ($)', en: 'Risk ($)', fa: 'ریسک ($)', ar: 'المخاطرة ($)', ru: 'Риск ($)', es: 'Riesgo ($)', pt: 'Risco ($)', de: 'Risiko ($)', fr: 'Risque ($)' },
  reward: { tr: 'Kazanç ($)', en: 'Reward ($)', fa: 'سود ($)', ar: 'المكافأة ($)', ru: 'Прибыль ($)', es: 'Ganancia ($)', pt: 'Ganho ($)', de: 'Gewinn ($)', fr: 'Gain ($)' },
  result: { tr: 'Sonuç', en: 'Result', fa: 'نتیجه', ar: 'النتيجة', ru: 'Результат', es: 'Resultado', pt: 'Resultado', de: 'Ergebnis', fr: 'Résultat' },
  resultOpen: { tr: 'Açık / Beklemede', en: 'Open / Pending', fa: 'باز / در انتظار', ar: 'مفتوح / معلق', ru: 'Открытая / Ожидает', es: 'Abierta / Pendiente', pt: 'Aberta / Pendente', de: 'Offen / Ausstehend', fr: 'Ouverte / En attente' },
  resultWin: { tr: 'Başarılı', en: 'Win', fa: 'موفق', ar: 'فوز', ru: 'Прибыль', es: 'Ganada', pt: 'Ganha', de: 'Gewinn', fr: 'Gagné' },
  resultLoss: { tr: 'Başarısız', en: 'Loss', fa: 'ناموفق', ar: 'خسارة', ru: 'Убыток', es: 'Perdida', pt: 'Perdida', de: 'Verlust', fr: 'Perdu' },
  resultManualWin: { tr: 'Karda manuel kapattım', en: 'Closed Manually (Profit)', fa: 'بسته شده دستی (سود)', ar: 'أغلقت يدوياً (ربح)', ru: 'Закрыта вручную (прибыль)', es: 'Cerrada manualmente (beneficio)', pt: 'Fechada manualmente (lucro)', de: 'Manuell geschlossen (Gewinn)', fr: 'Fermée manuellement (profit)' },
  resultManualLoss: { tr: 'Zararda manuel kapattım', en: 'Closed Manually (Loss)', fa: 'بسته شده دستی (ضرر)', ar: 'أغلقت يدوياً (خسارة)', ru: 'Закрыта вручную (убыток)', es: 'Cerrada manualmente (pérdida)', pt: 'Fechada manualmente (perda)', de: 'Manuell geschlossen (Verlust)', fr: 'Fermée manuellement (perte)' },
  preTrade: { tr: 'İşlem Öncesi', en: 'Pre-Trade', fa: 'قبل از معامله', ar: 'قبل الصفقة', ru: 'До сделки', es: 'Pre-operación', pt: 'Pré-operação', de: 'Vor dem Trade', fr: 'Avant le trade' },
  postTrade: { tr: 'İşlem Sonrası', en: 'Post-Trade', fa: 'بعد از معامله', ar: 'بعد الصفقة', ru: 'После сделки', es: 'Post-operación', pt: 'Pós-operação', de: 'Nach dem Trade', fr: 'Après le trade' },
  photos: { tr: 'Fotoğraflar', en: 'Photos', fa: 'عکس‌ها', ar: 'الصور', ru: 'Фото', es: 'Fotos', pt: 'Fotos', de: 'Fotos', fr: 'Photos' },
  photoUpload: { tr: 'Fotoğraf Yükle', en: 'Upload Photo', fa: 'آپلود عکس', ar: 'رفع صورة', ru: 'Загрузить фото', es: 'Subir foto', pt: 'Enviar foto', de: 'Foto hochladen', fr: 'Télécharger une photo' },
  notes: { tr: 'Not', en: 'Notes', fa: 'یادداشت', ar: 'الملاحظات', ru: 'Заметки', es: 'Notas', pt: 'Notas', de: 'Notizen', fr: 'Notes' },
  preNotesPlaceholder: { tr: 'İşleme girme nedeniniz, beklentileriniz...', en: 'Reason for entry, expectations...', fa: 'دلیل ورود به معامله، انتظارات...', ar: 'سبب الدخول، التوقعات...', ru: 'Причина входа, ожидания...', es: 'Razón de entrada, expectativas...', pt: 'Motivo de entrada, expectativas...', de: 'Grund für Einstieg, Erwartungen...', fr: "Raison d'entrée, attentes..." },
  postNotesPlaceholder: { tr: 'İşlem sonucu, yapılan hatalar, çıkarılan dersler...', en: 'Trade result, mistakes made, lessons learned...', fa: 'نتیجه معامله، اشتباهات، درس‌های گرفته شده...', ar: 'نتيجة الصفقة، الأخطاء المرتكبة، الدروس المستفادة...', ru: 'Результат сделки, ошибки, выводы...', es: 'Resultado, errores cometidos, lecciones aprendidas...', pt: 'Resultado, erros cometidos, lições aprendidas...', de: 'Ergebnis, Fehler, Lektionen...', fr: 'Résultat, erreurs, leçons apprises...' },
  saveButton: { tr: 'İşlemi Kaydet', en: 'Save Trade', fa: 'ثبت معامله', ar: 'حفظ الصفقة', ru: 'Сохранить сделку', es: 'Guardar operación', pt: 'Salvar operação', de: 'Trade speichern', fr: 'Enregistrer le trade' },
  pleaseSelectDate: { tr: 'Lütfen tarih seçin', en: 'Please select a date', fa: 'لطفاً تاریخ را انتخاب کنید', ar: 'الرجاء اختيار تاريخ', ru: 'Пожалуйста, выберите дату', es: 'Por favor seleccione una fecha', pt: 'Por favor selecione uma data', de: 'Bitte Datum auswählen', fr: 'Veuillez sélectionner une date' },
  emptyTitle: { tr: 'Henüz işlem yok', en: 'No trades yet', fa: 'هنوز معامله‌ای ثبت نشده', ar: 'لا توجد صفقات بعد', ru: 'Сделок пока нет', es: 'Aún no hay operaciones', pt: 'Ainda não há operações', de: 'Noch keine Trades', fr: 'Pas encore de trades' },
  emptyDesc: { tr: 'Yeni İşlem butonunu kullanarak ilk işleminizi kaydedin.', en: 'Use the New Trade button to record your first trade.', fa: 'برای ثبت اولین معامله از دکمه معامله جدید استفاده کنید.', ar: 'استخدم زر صفقة جديدة لتسجيل أول صفقة لك.', ru: 'Используйте кнопку "Новая сделка" для записи первой сделки.', es: 'Usa el botón Nueva operación para registrar tu primera operación.', pt: 'Use o botão Nova operação para registrar sua primeira operação.', de: 'Verwenden Sie die Schaltfläche "Neuer Trade", um Ihren ersten Trade zu erfassen.', fr: 'Utilisez le bouton Nouveau trade pour enregistrer votre premier trade.' },
  backToList: { tr: 'Listeye Dön', en: 'Back to List', fa: 'بازگشت به لیست', ar: 'العودة إلى القائمة', ru: 'Вернуться к списку', es: 'Volver a la lista', pt: 'Voltar à lista', de: 'Zurück zur Liste', fr: 'Retour à la liste' },
  riskRewardLabel: { tr: 'Risk / Kazanç', en: 'Risk / Reward', fa: 'ریسک / سود', ar: 'المخاطرة / المكافأة', ru: 'Риск / Прибыль', es: 'Riesgo / Ganancia', pt: 'Risco / Retorno', de: 'Risiko / Gewinn', fr: 'Risque / Gain' },
  deleteTrade: { tr: 'İşlemi Sil', en: 'Delete Trade', fa: 'حذف معامله', ar: 'حذف الصفقة', ru: 'Удалить сделку', es: 'Eliminar operación', pt: 'Excluir operação', de: 'Trade löschen', fr: 'Supprimer le trade' },
  noNotes: { tr: 'Not eklenmemiş.', en: 'No notes added.', fa: 'یادداشتی اضافه نشده است.', ar: 'لم تتم إضافة ملاحظات.', ru: 'Заметок нет.', es: 'No se han añadido notas.', pt: 'Nenhuma nota adicionada.', de: 'Keine Notizen hinzugefügt.', fr: 'Aucune note ajoutée.' },
  openStatus: { tr: 'Açık', en: 'Open', fa: 'باز', ar: 'مفتوح', ru: 'Открытая', es: 'Abierta', pt: 'Aberta', de: 'Offen', fr: 'Ouverte' },
  winStatus: { tr: 'Başarılı', en: 'Win', fa: 'موفق', ar: 'فوز', ru: 'Прибыль', es: 'Ganada', pt: 'Ganha', de: 'Gewinn', fr: 'Gagné' },
  lossStatus: { tr: 'Başarısız', en: 'Loss', fa: 'ناموفق', ar: 'خسارة', ru: 'Убыток', es: 'Perdida', pt: 'Perdida', de: 'Verlust', fr: 'Perdu' },
  statsTitle: { tr: 'İstatistikler', en: 'Statistics', fa: 'آمار', ar: 'الإحصائيات', ru: 'Статистика', es: 'Estadísticas', pt: 'Estatísticas', de: 'Statistiken', fr: 'Statistiques' },
  tradeCount: { tr: 'İşlem', en: 'Trades', fa: 'معامله', ar: 'الصفقات', ru: 'Сделки', es: 'Operaciones', pt: 'Operações', de: 'Trades', fr: 'Trades' },
  totalTrades: { tr: 'Toplam İşlem', en: 'Total Trades', fa: 'معاملات بسته شده', ar: 'إجمالي الصفقات', ru: 'Всего сделок', es: 'Total operaciones', pt: 'Total de operações', de: 'Trades gesamt', fr: 'Total des trades' },
  winRate: { tr: 'Kazanma Oranı', en: 'Win Rate', fa: 'نرخ برد', ar: 'نسبة الفوز', ru: 'Процент прибыльных', es: 'Tasa de éxito', pt: 'Taxa de acerto', de: 'Gewinnrate', fr: 'Taux de réussite' },
  netProfit: { tr: 'Net Kar/Zarar', en: 'Net PnL', fa: 'سود/زیان خالص', ar: 'صافي الربح/الخسارة', ru: 'Чистая прибыль/убыток', es: 'PnL neto', pt: 'PnL líquido', de: 'Netto-PnL', fr: 'PnL net' },
  profitFactor: { tr: 'Kar Faktörü', en: 'Profit Factor', fa: 'فاکتور سود', ar: 'معامل الربح', ru: 'Профит-фактор', es: 'Factor de beneficio', pt: 'Fator de lucro', de: 'Profit-Faktor', fr: 'Facteur de profit' },
  bestTrade: { tr: 'En İyi İşlem', en: 'Best Trade', fa: 'بهترین معامله', ar: 'أفضل صفقة', ru: 'Лучшая сделка', es: 'Mejor operación', pt: 'Melhor operação', de: 'Bester Trade', fr: 'Meilleur trade' },
  worstTrade: { tr: 'En Kötü İşlem', en: 'Worst Trade', fa: 'بدترین معامله', ar: 'أسوأ صفقة', ru: 'Худшая сделка', es: 'Peor operación', pt: 'Pior operação', de: 'Schlechtester Trade', fr: 'Pire trade' },
  avgRR: { tr: 'Ortalama R/R', en: 'Avg R/R', fa: 'میانگین R/R', ar: 'متوسط R/R', ru: 'Ср. R/R', es: 'R/R promedio', pt: 'R/R médio', de: 'Durchschn. R/R', fr: 'R/R moyen' },
  bestDay: { tr: 'En İyi Gün', en: 'Best Day', fa: 'بهترین روز', ar: 'أفضل يوم', ru: 'Лучший день', es: 'Mejor día', pt: 'Melhor dia', de: 'Bester Tag', fr: 'Meilleur jour' },
  currentStreak: { tr: 'Mevcut Seri', en: 'Current Streak', fa: 'سری فعلی', ar: 'السلسلة الحالية', ru: 'Текущая серия', es: 'Racha actual', pt: 'Sequência atual', de: 'Aktuelle Serie', fr: 'Série actuelle' },
  bestWinStreak: { tr: 'En İyi Kazanç Serisi', en: 'Best Win Streak', fa: 'بهترین سری برد', ar: 'أفضل سلسلة فوز', ru: 'Лучшая серия побед', es: 'Mejor racha ganadora', pt: 'Melhor sequência de ganhos', de: 'Beste Gewinnserie', fr: 'Meilleure série gagnante' },
  bestLossStreak: { tr: 'En Kötü Kayıp Serisi', en: 'Best Loss Streak', fa: 'بدترین سری باخت', ar: 'أسوأ سلسلة خسارة', ru: 'Худшая серия потерь', es: 'Peor racha perdedora', pt: 'Pior sequência de perdas', de: 'Schlechteste Verlustserie', fr: 'Pire série perdante' },
  maxDrawdown: { tr: 'Max Drawdown', en: 'Max Drawdown', fa: 'حداکثر افت', ar: 'أقصى تراجع', ru: 'Макс. просадка', es: 'Drawdown máximo', pt: 'Drawdown máximo', de: 'Max. Drawdown', fr: 'Drawdown maximum' },
  drawdownChart: { tr: 'Drawdown Grafiği', en: 'Drawdown Chart', fa: 'نمودار افت', ar: 'مخطط التراجع', ru: 'График просадки', es: 'Gráfico de drawdown', pt: 'Gráfico de drawdown', de: 'Drawdown-Chart', fr: 'Graphique de drawdown' },
  heatMap: { tr: 'Isı Haritası', en: 'Heat Map', fa: 'نقشه حرارتی', ar: 'خريطة الحرارة', ru: 'Тепловая карта', es: 'Mapa de calor', pt: 'Mapa de calor', de: 'Heatmap', fr: 'Carte thermique' },
  setupPerformance: { tr: 'Setup Performansı', en: 'Setup Performance', fa: 'عملکرد ستاپ', ar: 'أداء الإعداد', ru: 'Эффективность сетапа', es: 'Rendimiento del setup', pt: 'Desempenho do setup', de: 'Setup-Performance', fr: 'Performance du setup' },
  symbolPerformance: { tr: 'Sembol Performansı', en: 'Symbol Performance', fa: 'عملکرد نماد', ar: 'أداء الرمز', ru: 'Эффективность символа', es: 'Rendimiento del símbolo', pt: 'Desempenho do símbolo', de: 'Symbol-Performance', fr: 'Performance du symbole' },
  profitable: { tr: 'Karlı', en: 'Profitable', fa: 'سودآور', ar: 'مربح', ru: 'Прибыльные', es: 'Rentable', pt: 'Lucrativo', de: 'Profitabel', fr: 'Profitable' },
  losing: { tr: 'Zararlı', en: 'Losing', fa: 'زیان‌ده', ar: 'خاسر', ru: 'Убыточные', es: 'Perdedora', pt: 'Com perda', de: 'Verlustreich', fr: 'Perdant' },
  cumulativePnl: { tr: 'Kümülatif PnL', en: 'Cumulative PnL', fa: 'سود/زیان انباشته', ar: 'PnL التراكمي', ru: 'Накопленная прибыль', es: 'PnL acumulado', pt: 'PnL acumulado', de: 'Kumulativer PnL', fr: 'PnL cumulatif' },
  tradePnl: { tr: 'İşlem PnL', en: 'Trade PnL', fa: 'سود/زیان معامله', ar: 'PnL الصفقة', ru: 'Прибыль по сделке', es: 'PnL de operación', pt: 'PnL da operação', de: 'Trade-PnL', fr: 'PnL du trade' },
  sessionStats: { tr: 'Oturum Başarı Oranları', en: 'Session Win Rates', fa: 'نرخ برد جلسات', ar: 'معدلات الفوز في الجلسة', ru: 'Процент побед по сессиям', es: 'Tasas de éxito por sesión', pt: 'Taxas de acerto por sessão', de: 'Sitzungs-Gewinnraten', fr: 'Taux de réussite par session' },
  dayStats: { tr: 'Günlük Başarı Oranları', en: 'Daily Win Rates', fa: 'نرخ برد روزانه', ar: 'معدلات الفوز اليومية', ru: 'Дневные показатели побед', es: 'Tasas de éxito diarias', pt: 'Taxas de acerto diárias', de: 'Tägliche Gewinnraten', fr: 'Taux de réussite quotidiens' },
  asianSession: { tr: 'Asya', en: 'Asian', fa: 'آسیا', ar: 'آسيا', ru: 'Азия', es: 'Asia', pt: 'Ásia', de: 'Asien', fr: 'Asie' },
  londonSession: { tr: 'Londra', en: 'London', fa: 'لندن', ar: 'لندن', ru: 'Лондон', es: 'Londres', pt: 'Londres', de: 'London', fr: 'Londres' },
  nySession: { tr: 'New York', en: 'New York', fa: 'نیویورک', ar: 'نيويورك', ru: 'Нью-Йорк', es: 'Nueva York', pt: 'Nova York', de: 'New York', fr: 'New York' },
  monday: { tr: 'Pazartesi', en: 'Monday', fa: 'دوشنبه', ar: 'الاثنين', ru: 'Понедельник', es: 'Lunes', pt: 'Segunda', de: 'Montag', fr: 'Lundi' },
  tuesday: { tr: 'Salı', en: 'Tuesday', fa: 'سه‌شنبه', ar: 'الثلاثاء', ru: 'Вторник', es: 'Martes', pt: 'Terça', de: 'Dienstag', fr: 'Mardi' },
  wednesday: { tr: 'Çarşamba', en: 'Wednesday', fa: 'چهارشنبه', ar: 'الأربعاء', ru: 'Среда', es: 'Miércoles', pt: 'Quarta', de: 'Mittwoch', fr: 'Mercredi' },
  thursday: { tr: 'Perşembe', en: 'Thursday', fa: 'پنج‌شنبه', ar: 'الخميس', ru: 'Четверг', es: 'Jueves', pt: 'Quinta', de: 'Donnerstag', fr: 'Jeudi' },
  friday: { tr: 'Cuma', en: 'Friday', fa: 'جمعه', ar: 'الجمعة', ru: 'Пятница', es: 'Viernes', pt: 'Sexta', de: 'Freitag', fr: 'Vendredi' },
  saturday: { tr: 'Cumartesi', en: 'Saturday', fa: 'شنبه', ar: 'السبت', ru: 'Суббота', es: 'Sábado', pt: 'Sábado', de: 'Samstag', fr: 'Samedi' },
  sunday: { tr: 'Pazar', en: 'Sunday', fa: 'یکشنبه', ar: 'الأحد', ru: 'Воскресенье', es: 'Domingo', pt: 'Domingo', de: 'Sonntag', fr: 'Dimanche' },
  accounts: { tr: 'Hesaplar', en: 'Accounts', fa: 'حساب‌ها', ar: 'الحسابات', ru: 'Счета', es: 'Cuentas', pt: 'Contas', de: 'Konten', fr: 'Comptes' },
  deleteAccountTitle: { tr: "Journal'ı Sil", en: 'Delete Journal', fa: 'حذف ژورنال', ar: 'حذف السجل', ru: 'Удалить журнал', es: 'Eliminar diario', pt: 'Excluir diário', de: 'Journal löschen', fr: 'Supprimer le journal' },
  deleteAccountDesc: { tr: "Bu journal'ı ve içindeki tüm işlemleri silmek istediğinize emin misiniz? Bu işlem geri alınamaz.", en: 'Are you sure you want to delete this journal and all its trades? This action cannot be undone.', fa: 'آیا مطمئن هستید که می‌خواهید این ژورنال و تمام معاملات آن را حذف کنید؟ این عمل غیرقابل بازگشت است.', ar: 'هل أنت متأكد أنك تريد حذف هذا السجل وجميع صفقاته؟ لا يمكن التراجع عن هذا الإجراء.', ru: 'Вы уверены, что хотите удалить этот журнал и все его сделки? Это действие нельзя отменить.', es: '¿Estás seguro de que quieres eliminar este diario y todas sus operaciones? Esta acción no se puede deshacer.', pt: 'Tem certeza que deseja excluir este diário e todas as suas operações? Esta ação não pode ser desfeita.', de: 'Sind Sie sicher, dass Sie dieses Journal und alle Trades löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.', fr: 'Êtes-vous sûr de vouloir supprimer ce journal et tous ses trades ? Cette action ne peut pas être annulée.' },
  delete: { tr: 'Sil', en: 'Delete', fa: 'حذف', ar: 'حذف', ru: 'Удалить', es: 'Eliminar', pt: 'Excluir', de: 'Löschen', fr: 'Supprimer' },
  cancel: { tr: 'İptal', en: 'Cancel', fa: 'لغو', ar: 'إلغاء', ru: 'Отмена', es: 'Cancelar', pt: 'Cancelar', de: 'Abbrechen', fr: 'Annuler' },
  save: { tr: 'Kaydet', en: 'Save', fa: 'ذخیره', ar: 'حفظ', ru: 'Сохранить', es: 'Guardar', pt: 'Salvar', de: 'Speichern', fr: 'Enregistrer' },
  aiAnalyzing: { tr: 'Yapay zeka analiz yapıyor...', en: 'AI is analyzing...', fa: 'هوش مصنوعی در حال تحلیل است...', ar: 'الذكاء الاصطناعي يحلل...', ru: 'ИИ анализирует...', es: 'La IA está analizando...', pt: 'A IA está analisando...', de: 'KI analysiert...', fr: "L'IA analyse..." },
  aiAnalyzeBtn: { tr: '✨ Analiz Et', en: '✨ Analyze', fa: '✨ تحلیل', ar: '✨ تحليل', ru: '✨ Анализ', es: '✨ Analizar', pt: '✨ Analisar', de: '✨ Analysieren', fr: '✨ Analyser' },
  aiAnalyzeLoading: { tr: '⏳ Analiz yapılıyor...', en: '⏳ Analyzing...', fa: '⏳ در حال تحلیل...', ar: '⏳ جاري التحليل...', ru: '⏳ Анализируется...', es: '⏳ Analizando...', pt: '⏳ Analisando...', de: '⏳ Wird analysiert...', fr: '⏳ Analyse en cours...' },
  aiAnalyzeDesc: { tr: 'Tüm trade verilerinizi AI ile analiz edin. Güçlü/zayıf yönler, setup performansı ve kişisel öneriler alın.', en: 'Analyze all your trade data with AI. Get strengths/weaknesses, setup performance and personal recommendations.', fa: 'تمام داده‌های معاملاتی خود را با هوش مصنوعی تحلیل کنید.', ar: 'حلل جميع بيانات تداولك بالذكاء الاصطناعي. احصل على نقاط القوة/الضعف وتوصيات شخصية.', ru: 'Анализируйте все данные сделок с помощью ИИ. Получите сильные/слабые стороны и рекомендации.', es: 'Analiza todos tus datos de trading con IA. Obtén fortalezas/debilidades y recomendaciones personales.', pt: 'Analise todos os seus dados de trading com IA. Obtenha pontos fortes/fracos e recomendações pessoais.', de: 'Analysieren Sie alle Trade-Daten mit KI. Erhalten Sie Stärken/Schwächen und persönliche Empfehlungen.', fr: 'Analysez toutes vos données de trading avec l\'IA. Obtenez forces/faiblesses et recommandations personnelles.' },
  goalsTitle: { tr: 'Hedefler & Kurallar', en: 'Goals & Rules', fa: 'اهداف و قوانین', ar: 'الأهداف والقواعد', ru: 'Цели и правила', es: 'Objetivos y reglas', pt: 'Metas e regras', de: 'Ziele & Regeln', fr: 'Objectifs et règles' },
  editGoals: { tr: 'Hedefleri Düzenle', en: 'Edit Goals', fa: 'ویرایش اهداف', ar: 'تعديل الأهداف', ru: 'Изменить цели', es: 'Editar objetivos', pt: 'Editar metas', de: 'Ziele bearbeiten', fr: 'Modifier les objectifs' },
  monthlyPnLGoal: { tr: 'Aylık PnL Hedefi', en: 'Monthly PnL Goal', fa: 'هدف سود ماهانه', ar: 'هدف الربح الشهري', ru: 'Цель по прибыли в месяц', es: 'Meta de PnL mensual', pt: 'Meta de PnL mensal', de: 'Monatliches PnL-Ziel', fr: 'Objectif PnL mensuel' },
  winRateGoal: { tr: 'Win Rate Hedefi', en: 'Win Rate Goal', fa: 'هدف نرخ برد', ar: 'هدف نسبة الفوز', ru: 'Цель по проценту побед', es: 'Meta de tasa de éxito', pt: 'Meta de taxa de acerto', de: 'Gewinnraten-Ziel', fr: 'Objectif taux de réussite' },
  maxDailyTrades: { tr: 'Günlük Max İşlem', en: 'Max Daily Trades', fa: 'حداکثر معاملات روزانه', ar: 'الحد الأقصى للصفقات اليومية', ru: 'Макс. сделок в день', es: 'Máximo de operaciones diarias', pt: 'Máximo de operações diárias', de: 'Max. tägliche Trades', fr: 'Max trades quotidiens' },
  maxRiskPerTrade: { tr: 'İşlem Başı Max Risk', en: 'Max Risk Per Trade', fa: 'حداکثر ریسک هر معامله', ar: 'الحد الأقصى للمخاطرة لكل صفقة', ru: 'Макс. риск на сделку', es: 'Riesgo máximo por operación', pt: 'Risco máximo por operação', de: 'Max. Risiko pro Trade', fr: 'Risque maximum par trade' },
  maxRiskDesc: { tr: 'Bu limitin üzerinde risk alan işlemler ihlal olarak işaretlenir.', en: 'Trades exceeding this limit will be flagged as violations.', fa: 'معاملات بیش از این حد به عنوان نقض علامت‌گذاری می‌شوند.', ar: 'ستُعلَّم الصفقات التي تتجاوز هذا الحد كانتهاكات.', ru: 'Сделки с риском выше лимита будут отмечены как нарушения.', es: 'Las operaciones que superen este límite se marcarán como infracciones.', pt: 'Operações que excedam este limite serão marcadas como violações.', de: 'Trades, die dieses Limit überschreiten, werden als Verstöße markiert.', fr: 'Les trades dépassant cette limite seront signalés comme violations.' },
  noTradeHours: { tr: 'İşlem Yasak Saatler', en: 'No-Trade Hours', fa: 'ساعات ممنوع معامله', ar: 'ساعات عدم التداول', ru: 'Часы без торговли', es: 'Horas sin operar', pt: 'Horas sem operar', de: 'Handelsfreie Stunden', fr: 'Heures sans trading' },
  noTradeHoursStart: { tr: 'Yasak Başlangıç Saati', en: 'No-Trade Start', fa: 'شروع ساعت ممنوع', ar: 'بداية وقت عدم التداول', ru: 'Начало запретных часов', es: 'Inicio de horas sin operar', pt: 'Início das horas sem operar', de: 'Start der handelsfreien Zeit', fr: 'Début des heures sans trading' },
  noTradeHoursEnd: { tr: 'Yasak Bitiş Saati', en: 'No-Trade End', fa: 'پایان ساعت ممنوع', ar: 'نهاية وقت عدم التداول', ru: 'Конец запретных часов', es: 'Fin de horas sin operar', pt: 'Fim das horas sem operar', de: 'Ende der handelsfreien Zeit', fr: 'Fin des heures sans trading' },
  noTradeHoursDesc: { tr: 'Bu saatler arasında açılan işlemler ihlal olarak işaretlenir.', en: 'Trades opened during these hours will be flagged as violations.', fa: 'معاملات باز شده در این ساعات به عنوان نقض علامت‌گذاری می‌شوند.', ar: 'ستُعلَّم الصفقات المفتوحة خلال هذه الساعات كانتهاكات.', ru: 'Сделки, открытые в эти часы, будут отмечены как нарушения.', es: 'Las operaciones abiertas durante estas horas se marcarán como infracciones.', pt: 'Operações abertas durante estas horas serão marcadas como violações.', de: 'Trades in diesen Stunden werden als Verstöße markiert.', fr: 'Les trades ouverts pendant ces heures seront signalés comme violations.' },
  notSet: { tr: 'Belirlenmedi', en: 'Not set', fa: 'تنظیم نشده', ar: 'غير محدد', ru: 'Не задано', es: 'No establecido', pt: 'Não definido', de: 'Nicht gesetzt', fr: 'Non défini' },
  violations: { tr: 'Kural İhlalleri', en: 'Rule Violations', fa: 'نقض قوانین', ar: 'انتهاكات القواعد', ru: 'Нарушения правил', es: 'Infracciones de reglas', pt: 'Violações de regras', de: 'Regelverstoße', fr: 'Violations de règles' },
  noViolations: { tr: 'Tüm kurallara uyuluyor! 🎉', en: 'All rules followed! 🎉', fa: 'همه قوانین رعایت شده! 🎉', ar: 'تم اتباع جميع القواعد! 🎉', ru: 'Все правила соблюдены! 🎉', es: '¡Todas las reglas seguidas! 🎉', pt: 'Todas as regras seguidas! 🎉', de: 'Alle Regeln befolgt! 🎉', fr: 'Toutes les règles respectées ! 🎉' },
  noGoalsTitle: { tr: 'Henüz hedef belirlenmedi', en: 'No goals set yet', fa: 'هنوز هدفی تعیین نشده', ar: 'لم يتم تحديد أهداف بعد', ru: 'Цели ещё не заданы', es: 'Aún no hay objetivos establecidos', pt: 'Ainda não há metas definidas', de: 'Noch keine Ziele gesetzt', fr: 'Aucun objectif défini encore' },
  noGoalsDesc: { tr: 'Aylık hedefler ve kurallar belirleyerek disiplininizi artırın.', en: 'Set monthly goals and rules to improve your discipline.', fa: 'اهداف ماهانه و قوانین تعیین کنید تا انضباط خود را بهبود بخشید.', ar: 'حدد أهدافاً وقواعد شهرية لتحسين انضباطك.', ru: 'Установите ежемесячные цели и правила для улучшения дисциплины.', es: 'Establece metas y reglas mensuales para mejorar tu disciplina.', pt: 'Defina metas e regras mensais para melhorar sua disciplina.', de: 'Setzen Sie monatliche Ziele und Regeln zur Verbesserung Ihrer Disziplin.', fr: 'Définissez des objectifs et règles mensuels pour améliorer votre discipline.' },
  noMonthlyPnLGoal: { tr: 'Aylık PnL hedefi yok', en: 'No monthly PnL goal', fa: 'هدف سود ماهانه وجود ندارد', ar: 'لا يوجد هدف PnL شهري', ru: 'Нет цели по месячной прибыли', es: 'Sin meta de PnL mensual', pt: 'Sem meta de PnL mensal', de: 'Kein monatliches PnL-Ziel', fr: 'Pas d\'objectif PnL mensuel' },
  noWinRateGoal: { tr: 'Win rate hedefi yok', en: 'No win rate goal', fa: 'هدف نرخ برد وجود ندارد', ar: 'لا يوجد هدف لنسبة الفوز', ru: 'Нет цели по проценту побед', es: 'Sin meta de tasa de éxito', pt: 'Sem meta de taxa de acerto', de: 'Kein Gewinnraten-Ziel', fr: 'Pas d\'objectif de taux de réussite' },
  noMaxDailyTrades: { tr: 'Günlük limit yok', en: 'No daily limit', fa: 'محدودیت روزانه وجود ندارد', ar: 'لا يوجد حد يومي', ru: 'Нет дневного лимита', es: 'Sin límite diario', pt: 'Sem limite diário', de: 'Kein Tageslimit', fr: 'Pas de limite quotidienne' },
  noMaxRisk: { tr: 'Risk limiti yok', en: 'No risk limit', fa: 'محدودیت ریسک وجود ندارد', ar: 'لا يوجد حد للمخاطرة', ru: 'Нет лимита риска', es: 'Sin límite de riesgo', pt: 'Sem limite de risco', de: 'Kein Risikolimit', fr: 'Pas de limite de risque' },
  maxDailyTradesViolation: { tr: 'Günlük işlem limiti aşıldı', en: 'Daily trade limit exceeded', fa: 'محدودیت معاملات روزانه تجاوز شد', ar: 'تم تجاوز الحد اليومي للصفقات', ru: 'Превышен дневной лимит сделок', es: 'Límite diario de operaciones superado', pt: 'Limite diário de operações excedido', de: 'Tägliches Trade-Limit überschritten', fr: 'Limite quotidienne de trades dépassée' },
  maxRiskViolation: { tr: 'Risk limiti aşılan işlemler var', en: 'Trades exceeding risk limit', fa: 'معاملاتی که از حد ریسک تجاوز کرده‌اند', ar: 'صفقات تتجاوز حد المخاطرة', ru: 'Сделки с превышением лимита риска', es: 'Operaciones que superan el límite de riesgo', pt: 'Operações que excedem o limite de risco', de: 'Trades überschreiten Risikolimit', fr: 'Trades dépassant la limite de risque' },
  noTradeHoursViolation: { tr: 'Yasak saatlerde işlem yapıldı', en: 'Trades during no-trade hours', fa: 'معاملات در ساعات ممنوع', ar: 'صفقات خلال ساعات عدم التداول', ru: 'Сделки в запретные часы', es: 'Operaciones durante horas sin operar', pt: 'Operações durante horas sem operar', de: 'Trades in handelsfreien Stunden', fr: 'Trades pendant les heures sans trading' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');
  const t = (key: keyof typeof translations) => translations[key]?.[language] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
